-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filtering_network is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_V_ap_vld : IN STD_LOGIC;
    input_V : IN STD_LOGIC_VECTOR (191 downto 0);
    layer8_out_0_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_0_V_ap_vld : OUT STD_LOGIC;
    layer8_out_1_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_1_V_ap_vld : OUT STD_LOGIC;
    layer8_out_2_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_2_V_ap_vld : OUT STD_LOGIC;
    layer8_out_3_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_3_V_ap_vld : OUT STD_LOGIC;
    layer8_out_4_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_4_V_ap_vld : OUT STD_LOGIC;
    layer8_out_5_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_5_V_ap_vld : OUT STD_LOGIC;
    layer8_out_6_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_6_V_ap_vld : OUT STD_LOGIC;
    layer8_out_7_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_7_V_ap_vld : OUT STD_LOGIC;
    layer8_out_8_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_8_V_ap_vld : OUT STD_LOGIC;
    layer8_out_9_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_9_V_ap_vld : OUT STD_LOGIC;
    layer8_out_10_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_10_V_ap_vld : OUT STD_LOGIC;
    layer8_out_11_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_11_V_ap_vld : OUT STD_LOGIC;
    layer8_out_12_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_12_V_ap_vld : OUT STD_LOGIC;
    layer8_out_13_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_13_V_ap_vld : OUT STD_LOGIC;
    layer8_out_14_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_14_V_ap_vld : OUT STD_LOGIC;
    layer8_out_15_V : OUT STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_15_V_ap_vld : OUT STD_LOGIC;
    const_size_in_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    const_size_in_1_ap_vld : OUT STD_LOGIC;
    const_size_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    const_size_out_1_ap_vld : OUT STD_LOGIC );
end;


architecture behav of filtering_network is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "filtering_network,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku115-flvb2104-2-i,HLS_INPUT_CLOCK=12.500000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=10.273750,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=8,HLS_SYN_DSP=150,HLS_SYN_FF=1305,HLS_SYN_LUT=29451,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv192_lc_1 : STD_LOGIC_VECTOR (191 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal input_V_ap_vld_in_sig : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal input_V_preg : STD_LOGIC_VECTOR (191 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal input_V_in_sig : STD_LOGIC_VECTOR (191 downto 0);
    signal input_V_ap_vld_preg : STD_LOGIC := '0';
    signal input_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer2_out_0_V_reg_828 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_1_V_reg_833 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_2_V_reg_838 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_3_V_reg_843 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_4_V_reg_848 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_5_V_reg_853 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_6_V_reg_858 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_7_V_reg_863 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_8_V_reg_868 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_9_V_reg_873 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_10_V_reg_878 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_11_V_reg_883 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_12_V_reg_888 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_13_V_reg_893 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_14_V_reg_898 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer2_out_15_V_reg_903 : STD_LOGIC_VECTOR (20 downto 0);
    signal layer3_out_0_V_reg_908 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_1_V_reg_913 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_2_V_reg_918 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_3_V_reg_923 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_4_V_reg_928 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_5_V_reg_933 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_6_V_reg_938 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_7_V_reg_943 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_8_V_reg_948 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_9_V_reg_953 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_10_V_reg_958 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_11_V_reg_963 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_12_V_reg_968 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_13_V_reg_973 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_14_V_reg_978 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_15_V_reg_983 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_16_V_reg_988 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_17_V_reg_993 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_18_V_reg_998 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_19_V_reg_1003 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_20_V_reg_1008 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_21_V_reg_1013 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_22_V_reg_1018 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_23_V_reg_1023 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_24_V_reg_1028 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_25_V_reg_1033 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_26_V_reg_1038 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_27_V_reg_1043 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_28_V_reg_1048 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_29_V_reg_1053 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_30_V_reg_1058 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer3_out_31_V_reg_1063 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_0_V_reg_1068 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_1_V_reg_1073 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_2_V_reg_1078 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_3_V_reg_1083 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_4_V_reg_1088 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_5_V_reg_1093 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_6_V_reg_1098 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_7_V_reg_1103 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_8_V_reg_1108 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_9_V_reg_1113 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_10_V_reg_1118 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_11_V_reg_1123 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_12_V_reg_1128 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_13_V_reg_1133 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_14_V_reg_1138 : STD_LOGIC_VECTOR (15 downto 0);
    signal layer6_out_15_V_reg_1143 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_ready : STD_LOGIC;
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_ready : STD_LOGIC;
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_20 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_21 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_22 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_30 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_31 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_sigmoid_fu_268_ap_start : STD_LOGIC;
    signal grp_sigmoid_fu_268_ap_done : STD_LOGIC;
    signal grp_sigmoid_fu_268_ap_idle : STD_LOGIC;
    signal grp_sigmoid_fu_268_ap_ready : STD_LOGIC;
    signal grp_sigmoid_fu_268_ap_ce : STD_LOGIC;
    signal grp_sigmoid_fu_268_ap_return_0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_4 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_5 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_6 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_7 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_8 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_9 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_10 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_11 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_12 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_13 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_14 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sigmoid_fu_268_ap_return_15 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call126 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call126 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call126 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call126 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call126 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp107 : BOOLEAN;
    signal call_ret2_relu_fu_290_ap_ready : STD_LOGIC;
    signal call_ret2_relu_fu_290_ap_return_0 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_3 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_4 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_5 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_6 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_7 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_8 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_9 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_10 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_11 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_12 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_13 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_14 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_15 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_16 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_17 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_18 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_19 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_20 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_21 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_22 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_23 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_24 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_25 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_26 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_27 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_28 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_29 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_30 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret2_relu_fu_290_ap_return_31 : STD_LOGIC_VECTOR (6 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_ready : STD_LOGIC;
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_0 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_1 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_2 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_3 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_4 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_5 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_6 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_7 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_8 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_9 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_10 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_11 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_12 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_13 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_14 : STD_LOGIC_VECTOR (20 downto 0);
    signal call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_15 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_sigmoid_fu_268_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component dense_latency_0_0_0_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_16_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_17_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_18_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_19_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_20_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_21_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_22_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_24_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_27_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_28_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_29_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_30_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        data_31_V_read : IN STD_LOGIC_VECTOR (6 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dense_latency_0_0_0_1 IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (20 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component sigmoid IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (4 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component relu IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_16_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_18_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_19_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_20_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_21_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_22_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_24_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_27_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_28_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_29_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_30_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_31_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (6 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component normalize_0_0_0_0_0_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_V_read : IN STD_LOGIC_VECTOR (191 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (20 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;



begin
    call_ret3_dense_latency_0_0_0_s_fu_212 : component dense_latency_0_0_0_s
    port map (
        ap_ready => call_ret3_dense_latency_0_0_0_s_fu_212_ap_ready,
        data_0_V_read => call_ret2_relu_fu_290_ap_return_0,
        data_1_V_read => call_ret2_relu_fu_290_ap_return_1,
        data_2_V_read => call_ret2_relu_fu_290_ap_return_2,
        data_3_V_read => call_ret2_relu_fu_290_ap_return_3,
        data_4_V_read => call_ret2_relu_fu_290_ap_return_4,
        data_5_V_read => call_ret2_relu_fu_290_ap_return_5,
        data_6_V_read => call_ret2_relu_fu_290_ap_return_6,
        data_7_V_read => call_ret2_relu_fu_290_ap_return_7,
        data_8_V_read => call_ret2_relu_fu_290_ap_return_8,
        data_9_V_read => call_ret2_relu_fu_290_ap_return_9,
        data_10_V_read => call_ret2_relu_fu_290_ap_return_10,
        data_11_V_read => call_ret2_relu_fu_290_ap_return_11,
        data_12_V_read => call_ret2_relu_fu_290_ap_return_12,
        data_13_V_read => call_ret2_relu_fu_290_ap_return_13,
        data_14_V_read => call_ret2_relu_fu_290_ap_return_14,
        data_15_V_read => call_ret2_relu_fu_290_ap_return_15,
        data_16_V_read => call_ret2_relu_fu_290_ap_return_16,
        data_17_V_read => call_ret2_relu_fu_290_ap_return_17,
        data_18_V_read => call_ret2_relu_fu_290_ap_return_18,
        data_19_V_read => call_ret2_relu_fu_290_ap_return_19,
        data_20_V_read => call_ret2_relu_fu_290_ap_return_20,
        data_21_V_read => call_ret2_relu_fu_290_ap_return_21,
        data_22_V_read => call_ret2_relu_fu_290_ap_return_22,
        data_23_V_read => call_ret2_relu_fu_290_ap_return_23,
        data_24_V_read => call_ret2_relu_fu_290_ap_return_24,
        data_25_V_read => call_ret2_relu_fu_290_ap_return_25,
        data_26_V_read => call_ret2_relu_fu_290_ap_return_26,
        data_27_V_read => call_ret2_relu_fu_290_ap_return_27,
        data_28_V_read => call_ret2_relu_fu_290_ap_return_28,
        data_29_V_read => call_ret2_relu_fu_290_ap_return_29,
        data_30_V_read => call_ret2_relu_fu_290_ap_return_30,
        data_31_V_read => call_ret2_relu_fu_290_ap_return_31,
        ap_return_0 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_0,
        ap_return_1 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_1,
        ap_return_2 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_2,
        ap_return_3 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_3,
        ap_return_4 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_4,
        ap_return_5 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_5,
        ap_return_6 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_6,
        ap_return_7 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_7,
        ap_return_8 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_8,
        ap_return_9 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_9,
        ap_return_10 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_10,
        ap_return_11 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_11,
        ap_return_12 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_12,
        ap_return_13 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_13,
        ap_return_14 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_14,
        ap_return_15 => call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_15);

    call_ret1_dense_latency_0_0_0_1_fu_248 : component dense_latency_0_0_0_1
    port map (
        ap_ready => call_ret1_dense_latency_0_0_0_1_fu_248_ap_ready,
        data_0_V_read => layer2_out_0_V_reg_828,
        data_1_V_read => layer2_out_1_V_reg_833,
        data_2_V_read => layer2_out_2_V_reg_838,
        data_3_V_read => layer2_out_3_V_reg_843,
        data_4_V_read => layer2_out_4_V_reg_848,
        data_5_V_read => layer2_out_5_V_reg_853,
        data_6_V_read => layer2_out_6_V_reg_858,
        data_7_V_read => layer2_out_7_V_reg_863,
        data_8_V_read => layer2_out_8_V_reg_868,
        data_9_V_read => layer2_out_9_V_reg_873,
        data_10_V_read => layer2_out_10_V_reg_878,
        data_11_V_read => layer2_out_11_V_reg_883,
        data_12_V_read => layer2_out_12_V_reg_888,
        data_13_V_read => layer2_out_13_V_reg_893,
        data_14_V_read => layer2_out_14_V_reg_898,
        data_15_V_read => layer2_out_15_V_reg_903,
        ap_return_0 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_0,
        ap_return_1 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_1,
        ap_return_2 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_2,
        ap_return_3 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_3,
        ap_return_4 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_4,
        ap_return_5 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_5,
        ap_return_6 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_6,
        ap_return_7 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_7,
        ap_return_8 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_8,
        ap_return_9 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_9,
        ap_return_10 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_10,
        ap_return_11 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_11,
        ap_return_12 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_12,
        ap_return_13 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_13,
        ap_return_14 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_14,
        ap_return_15 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_15,
        ap_return_16 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_16,
        ap_return_17 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_17,
        ap_return_18 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_18,
        ap_return_19 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_19,
        ap_return_20 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_20,
        ap_return_21 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_21,
        ap_return_22 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_22,
        ap_return_23 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_23,
        ap_return_24 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_24,
        ap_return_25 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_25,
        ap_return_26 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_26,
        ap_return_27 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_27,
        ap_return_28 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_28,
        ap_return_29 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_29,
        ap_return_30 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_30,
        ap_return_31 => call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_31);

    grp_sigmoid_fu_268 : component sigmoid
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sigmoid_fu_268_ap_start,
        ap_done => grp_sigmoid_fu_268_ap_done,
        ap_idle => grp_sigmoid_fu_268_ap_idle,
        ap_ready => grp_sigmoid_fu_268_ap_ready,
        ap_ce => grp_sigmoid_fu_268_ap_ce,
        data_0_V_read => layer6_out_0_V_reg_1068,
        data_1_V_read => layer6_out_1_V_reg_1073,
        data_2_V_read => layer6_out_2_V_reg_1078,
        data_3_V_read => layer6_out_3_V_reg_1083,
        data_4_V_read => layer6_out_4_V_reg_1088,
        data_5_V_read => layer6_out_5_V_reg_1093,
        data_6_V_read => layer6_out_6_V_reg_1098,
        data_7_V_read => layer6_out_7_V_reg_1103,
        data_8_V_read => layer6_out_8_V_reg_1108,
        data_9_V_read => layer6_out_9_V_reg_1113,
        data_10_V_read => layer6_out_10_V_reg_1118,
        data_11_V_read => layer6_out_11_V_reg_1123,
        data_12_V_read => layer6_out_12_V_reg_1128,
        data_13_V_read => layer6_out_13_V_reg_1133,
        data_14_V_read => layer6_out_14_V_reg_1138,
        data_15_V_read => layer6_out_15_V_reg_1143,
        ap_return_0 => grp_sigmoid_fu_268_ap_return_0,
        ap_return_1 => grp_sigmoid_fu_268_ap_return_1,
        ap_return_2 => grp_sigmoid_fu_268_ap_return_2,
        ap_return_3 => grp_sigmoid_fu_268_ap_return_3,
        ap_return_4 => grp_sigmoid_fu_268_ap_return_4,
        ap_return_5 => grp_sigmoid_fu_268_ap_return_5,
        ap_return_6 => grp_sigmoid_fu_268_ap_return_6,
        ap_return_7 => grp_sigmoid_fu_268_ap_return_7,
        ap_return_8 => grp_sigmoid_fu_268_ap_return_8,
        ap_return_9 => grp_sigmoid_fu_268_ap_return_9,
        ap_return_10 => grp_sigmoid_fu_268_ap_return_10,
        ap_return_11 => grp_sigmoid_fu_268_ap_return_11,
        ap_return_12 => grp_sigmoid_fu_268_ap_return_12,
        ap_return_13 => grp_sigmoid_fu_268_ap_return_13,
        ap_return_14 => grp_sigmoid_fu_268_ap_return_14,
        ap_return_15 => grp_sigmoid_fu_268_ap_return_15);

    call_ret2_relu_fu_290 : component relu
    port map (
        ap_ready => call_ret2_relu_fu_290_ap_ready,
        data_0_V_read => layer3_out_0_V_reg_908,
        data_1_V_read => layer3_out_1_V_reg_913,
        data_2_V_read => layer3_out_2_V_reg_918,
        data_3_V_read => layer3_out_3_V_reg_923,
        data_4_V_read => layer3_out_4_V_reg_928,
        data_5_V_read => layer3_out_5_V_reg_933,
        data_6_V_read => layer3_out_6_V_reg_938,
        data_7_V_read => layer3_out_7_V_reg_943,
        data_8_V_read => layer3_out_8_V_reg_948,
        data_9_V_read => layer3_out_9_V_reg_953,
        data_10_V_read => layer3_out_10_V_reg_958,
        data_11_V_read => layer3_out_11_V_reg_963,
        data_12_V_read => layer3_out_12_V_reg_968,
        data_13_V_read => layer3_out_13_V_reg_973,
        data_14_V_read => layer3_out_14_V_reg_978,
        data_15_V_read => layer3_out_15_V_reg_983,
        data_16_V_read => layer3_out_16_V_reg_988,
        data_17_V_read => layer3_out_17_V_reg_993,
        data_18_V_read => layer3_out_18_V_reg_998,
        data_19_V_read => layer3_out_19_V_reg_1003,
        data_20_V_read => layer3_out_20_V_reg_1008,
        data_21_V_read => layer3_out_21_V_reg_1013,
        data_22_V_read => layer3_out_22_V_reg_1018,
        data_23_V_read => layer3_out_23_V_reg_1023,
        data_24_V_read => layer3_out_24_V_reg_1028,
        data_25_V_read => layer3_out_25_V_reg_1033,
        data_26_V_read => layer3_out_26_V_reg_1038,
        data_27_V_read => layer3_out_27_V_reg_1043,
        data_28_V_read => layer3_out_28_V_reg_1048,
        data_29_V_read => layer3_out_29_V_reg_1053,
        data_30_V_read => layer3_out_30_V_reg_1058,
        data_31_V_read => layer3_out_31_V_reg_1063,
        ap_return_0 => call_ret2_relu_fu_290_ap_return_0,
        ap_return_1 => call_ret2_relu_fu_290_ap_return_1,
        ap_return_2 => call_ret2_relu_fu_290_ap_return_2,
        ap_return_3 => call_ret2_relu_fu_290_ap_return_3,
        ap_return_4 => call_ret2_relu_fu_290_ap_return_4,
        ap_return_5 => call_ret2_relu_fu_290_ap_return_5,
        ap_return_6 => call_ret2_relu_fu_290_ap_return_6,
        ap_return_7 => call_ret2_relu_fu_290_ap_return_7,
        ap_return_8 => call_ret2_relu_fu_290_ap_return_8,
        ap_return_9 => call_ret2_relu_fu_290_ap_return_9,
        ap_return_10 => call_ret2_relu_fu_290_ap_return_10,
        ap_return_11 => call_ret2_relu_fu_290_ap_return_11,
        ap_return_12 => call_ret2_relu_fu_290_ap_return_12,
        ap_return_13 => call_ret2_relu_fu_290_ap_return_13,
        ap_return_14 => call_ret2_relu_fu_290_ap_return_14,
        ap_return_15 => call_ret2_relu_fu_290_ap_return_15,
        ap_return_16 => call_ret2_relu_fu_290_ap_return_16,
        ap_return_17 => call_ret2_relu_fu_290_ap_return_17,
        ap_return_18 => call_ret2_relu_fu_290_ap_return_18,
        ap_return_19 => call_ret2_relu_fu_290_ap_return_19,
        ap_return_20 => call_ret2_relu_fu_290_ap_return_20,
        ap_return_21 => call_ret2_relu_fu_290_ap_return_21,
        ap_return_22 => call_ret2_relu_fu_290_ap_return_22,
        ap_return_23 => call_ret2_relu_fu_290_ap_return_23,
        ap_return_24 => call_ret2_relu_fu_290_ap_return_24,
        ap_return_25 => call_ret2_relu_fu_290_ap_return_25,
        ap_return_26 => call_ret2_relu_fu_290_ap_return_26,
        ap_return_27 => call_ret2_relu_fu_290_ap_return_27,
        ap_return_28 => call_ret2_relu_fu_290_ap_return_28,
        ap_return_29 => call_ret2_relu_fu_290_ap_return_29,
        ap_return_30 => call_ret2_relu_fu_290_ap_return_30,
        ap_return_31 => call_ret2_relu_fu_290_ap_return_31);

    call_ret_normalize_0_0_0_0_0_s_fu_326 : component normalize_0_0_0_0_0_s
    port map (
        ap_ready => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_ready,
        data_V_read => input_V_in_sig,
        ap_return_0 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_0,
        ap_return_1 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_1,
        ap_return_2 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_2,
        ap_return_3 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_3,
        ap_return_4 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_4,
        ap_return_5 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_5,
        ap_return_6 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_6,
        ap_return_7 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_7,
        ap_return_8 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_8,
        ap_return_9 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_9,
        ap_return_10 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_10,
        ap_return_11 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_11,
        ap_return_12 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_12,
        ap_return_13 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_13,
        ap_return_14 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_14,
        ap_return_15 => call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_15);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    grp_sigmoid_fu_268_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sigmoid_fu_268_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    grp_sigmoid_fu_268_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sigmoid_fu_268_ap_ready = ap_const_logic_1)) then 
                    grp_sigmoid_fu_268_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    input_V_ap_vld_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_V_ap_vld_preg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    input_V_ap_vld_preg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) and (input_V_ap_vld = ap_const_logic_1))) then 
                    input_V_ap_vld_preg <= input_V_ap_vld;
                end if; 
            end if;
        end if;
    end process;


    input_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_V_preg <= ap_const_lv192_lc_1;
            else
                if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) and (input_V_ap_vld = ap_const_logic_1))) then 
                    input_V_preg <= input_V;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                layer2_out_0_V_reg_828 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_0;
                layer2_out_10_V_reg_878 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_10;
                layer2_out_11_V_reg_883 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_11;
                layer2_out_12_V_reg_888 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_12;
                layer2_out_13_V_reg_893 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_13;
                layer2_out_14_V_reg_898 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_14;
                layer2_out_15_V_reg_903 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_15;
                layer2_out_1_V_reg_833 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_1;
                layer2_out_2_V_reg_838 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_2;
                layer2_out_3_V_reg_843 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_3;
                layer2_out_4_V_reg_848 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_4;
                layer2_out_5_V_reg_853 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_5;
                layer2_out_6_V_reg_858 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_6;
                layer2_out_7_V_reg_863 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_7;
                layer2_out_8_V_reg_868 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_8;
                layer2_out_9_V_reg_873 <= call_ret_normalize_0_0_0_0_0_s_fu_326_ap_return_9;
                layer3_out_0_V_reg_908 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_0;
                layer3_out_10_V_reg_958 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_10;
                layer3_out_11_V_reg_963 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_11;
                layer3_out_12_V_reg_968 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_12;
                layer3_out_13_V_reg_973 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_13;
                layer3_out_14_V_reg_978 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_14;
                layer3_out_15_V_reg_983 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_15;
                layer3_out_16_V_reg_988 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_16;
                layer3_out_17_V_reg_993 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_17;
                layer3_out_18_V_reg_998 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_18;
                layer3_out_19_V_reg_1003 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_19;
                layer3_out_1_V_reg_913 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_1;
                layer3_out_20_V_reg_1008 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_20;
                layer3_out_21_V_reg_1013 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_21;
                layer3_out_22_V_reg_1018 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_22;
                layer3_out_23_V_reg_1023 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_23;
                layer3_out_24_V_reg_1028 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_24;
                layer3_out_25_V_reg_1033 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_25;
                layer3_out_26_V_reg_1038 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_26;
                layer3_out_27_V_reg_1043 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_27;
                layer3_out_28_V_reg_1048 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_28;
                layer3_out_29_V_reg_1053 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_29;
                layer3_out_2_V_reg_918 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_2;
                layer3_out_30_V_reg_1058 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_30;
                layer3_out_31_V_reg_1063 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_31;
                layer3_out_3_V_reg_923 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_3;
                layer3_out_4_V_reg_928 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_4;
                layer3_out_5_V_reg_933 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_5;
                layer3_out_6_V_reg_938 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_6;
                layer3_out_7_V_reg_943 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_7;
                layer3_out_8_V_reg_948 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_8;
                layer3_out_9_V_reg_953 <= call_ret1_dense_latency_0_0_0_1_fu_248_ap_return_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                layer6_out_0_V_reg_1068 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_0;
                layer6_out_10_V_reg_1118 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_10;
                layer6_out_11_V_reg_1123 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_11;
                layer6_out_12_V_reg_1128 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_12;
                layer6_out_13_V_reg_1133 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_13;
                layer6_out_14_V_reg_1138 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_14;
                layer6_out_15_V_reg_1143 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_15;
                layer6_out_1_V_reg_1073 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_1;
                layer6_out_2_V_reg_1078 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_2;
                layer6_out_3_V_reg_1083 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_3;
                layer6_out_4_V_reg_1088 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_4;
                layer6_out_5_V_reg_1093 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_5;
                layer6_out_6_V_reg_1098 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_6;
                layer6_out_7_V_reg_1103 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_7;
                layer6_out_8_V_reg_1108 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_8;
                layer6_out_9_V_reg_1113 <= call_ret3_dense_latency_0_0_0_s_fu_212_ap_return_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp107_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp107 <= ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_ignore_call126_assign_proc : process(ap_start, input_V_ap_vld_in_sig)
    begin
                ap_block_state1_pp0_stage0_iter0_ignore_call126 <= ((ap_start = ap_const_logic_0) or (input_V_ap_vld_in_sig = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call126 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call126 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call126 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call126 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    const_size_in_1 <= ap_const_lv16_10;

    const_size_in_1_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            const_size_in_1_ap_vld <= ap_const_logic_1;
        else 
            const_size_in_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    const_size_out_1 <= ap_const_lv16_10;

    const_size_out_1_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            const_size_out_1_ap_vld <= ap_const_logic_1;
        else 
            const_size_out_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    grp_sigmoid_fu_268_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp107)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp107) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_sigmoid_fu_268_ap_ce <= ap_const_logic_1;
        else 
            grp_sigmoid_fu_268_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_sigmoid_fu_268_ap_start <= grp_sigmoid_fu_268_ap_start_reg;

    input_V_ap_vld_in_sig_assign_proc : process(input_V_ap_vld, input_V_ap_vld_preg)
    begin
        if ((input_V_ap_vld = ap_const_logic_1)) then 
            input_V_ap_vld_in_sig <= input_V_ap_vld;
        else 
            input_V_ap_vld_in_sig <= input_V_ap_vld_preg;
        end if; 
    end process;


    input_V_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, input_V_ap_vld, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            input_V_blk_n <= input_V_ap_vld;
        else 
            input_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_V_in_sig_assign_proc : process(input_V_ap_vld, input_V, input_V_preg)
    begin
        if ((input_V_ap_vld = ap_const_logic_1)) then 
            input_V_in_sig <= input_V;
        else 
            input_V_in_sig <= input_V_preg;
        end if; 
    end process;

    layer8_out_0_V <= grp_sigmoid_fu_268_ap_return_0;

    layer8_out_0_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_0_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_0_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_10_V <= grp_sigmoid_fu_268_ap_return_10;

    layer8_out_10_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_10_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_10_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_11_V <= grp_sigmoid_fu_268_ap_return_11;

    layer8_out_11_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_11_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_11_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_12_V <= grp_sigmoid_fu_268_ap_return_12;

    layer8_out_12_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_12_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_12_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_13_V <= grp_sigmoid_fu_268_ap_return_13;

    layer8_out_13_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_13_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_13_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_14_V <= grp_sigmoid_fu_268_ap_return_14;

    layer8_out_14_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_14_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_14_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_15_V <= grp_sigmoid_fu_268_ap_return_15;

    layer8_out_15_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_15_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_15_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_1_V <= grp_sigmoid_fu_268_ap_return_1;

    layer8_out_1_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_1_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_2_V <= grp_sigmoid_fu_268_ap_return_2;

    layer8_out_2_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_2_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_2_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_3_V <= grp_sigmoid_fu_268_ap_return_3;

    layer8_out_3_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_3_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_3_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_4_V <= grp_sigmoid_fu_268_ap_return_4;

    layer8_out_4_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_4_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_4_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_5_V <= grp_sigmoid_fu_268_ap_return_5;

    layer8_out_5_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_5_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_5_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_6_V <= grp_sigmoid_fu_268_ap_return_6;

    layer8_out_6_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_6_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_6_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_7_V <= grp_sigmoid_fu_268_ap_return_7;

    layer8_out_7_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_7_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_7_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_8_V <= grp_sigmoid_fu_268_ap_return_8;

    layer8_out_8_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_8_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_8_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    layer8_out_9_V <= grp_sigmoid_fu_268_ap_return_9;

    layer8_out_9_V_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            layer8_out_9_V_ap_vld <= ap_const_logic_1;
        else 
            layer8_out_9_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
