// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);


output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;

wire   [0:0] tmp_97_fu_208_p3;
wire   [7:0] zext_ln415_fu_216_p1;
wire   [7:0] trunc_ln_fu_190_p4;
wire   [6:0] trunc_ln415_s_fu_224_p4;
wire   [6:0] zext_ln415_32_fu_220_p1;
wire   [7:0] add_ln415_fu_234_p2;
wire   [0:0] tmp_98_fu_246_p3;
wire   [0:0] tmp_96_fu_200_p3;
wire   [0:0] xor_ln416_fu_254_p2;
wire   [4:0] p_Result_s_fu_274_p4;
wire   [0:0] and_ln416_fu_260_p2;
wire   [0:0] icmp_ln879_fu_284_p2;
wire   [0:0] icmp_ln768_fu_290_p2;
wire   [0:0] select_ln777_fu_296_p3;
wire   [0:0] tmp_99_fu_266_p3;
wire   [0:0] xor_ln785_fu_304_p2;
wire   [0:0] or_ln340_fu_310_p2;
wire   [6:0] add_ln416_fu_240_p2;
wire   [0:0] icmp_ln1494_fu_184_p2;
wire   [6:0] select_ln340_fu_316_p3;
wire   [6:0] select_ln1494_fu_324_p3;
wire   [0:0] tmp_101_fu_360_p3;
wire   [7:0] zext_ln415_33_fu_368_p1;
wire   [7:0] trunc_ln708_s_fu_342_p4;
wire   [6:0] trunc_ln415_1_fu_376_p4;
wire   [6:0] zext_ln415_34_fu_372_p1;
wire   [7:0] add_ln415_16_fu_386_p2;
wire   [0:0] tmp_102_fu_398_p3;
wire   [0:0] tmp_100_fu_352_p3;
wire   [0:0] xor_ln416_1_fu_406_p2;
wire   [4:0] p_Result_12_1_fu_426_p4;
wire   [0:0] and_ln416_1_fu_412_p2;
wire   [0:0] icmp_ln879_1_fu_436_p2;
wire   [0:0] icmp_ln768_1_fu_442_p2;
wire   [0:0] select_ln777_1_fu_448_p3;
wire   [0:0] tmp_103_fu_418_p3;
wire   [0:0] xor_ln785_1_fu_456_p2;
wire   [0:0] or_ln340_1_fu_462_p2;
wire   [6:0] add_ln416_1_fu_392_p2;
wire   [0:0] icmp_ln1494_1_fu_336_p2;
wire   [6:0] select_ln340_1_fu_468_p3;
wire   [6:0] select_ln1494_1_fu_476_p3;
wire   [0:0] tmp_105_fu_512_p3;
wire   [7:0] zext_ln415_35_fu_520_p1;
wire   [7:0] trunc_ln708_1_fu_494_p4;
wire   [6:0] trunc_ln415_2_fu_528_p4;
wire   [6:0] zext_ln415_36_fu_524_p1;
wire   [7:0] add_ln415_17_fu_538_p2;
wire   [0:0] tmp_106_fu_550_p3;
wire   [0:0] tmp_104_fu_504_p3;
wire   [0:0] xor_ln416_2_fu_558_p2;
wire   [4:0] p_Result_12_2_fu_578_p4;
wire   [0:0] and_ln416_2_fu_564_p2;
wire   [0:0] icmp_ln879_2_fu_588_p2;
wire   [0:0] icmp_ln768_2_fu_594_p2;
wire   [0:0] select_ln777_2_fu_600_p3;
wire   [0:0] tmp_107_fu_570_p3;
wire   [0:0] xor_ln785_2_fu_608_p2;
wire   [0:0] or_ln340_2_fu_614_p2;
wire   [6:0] add_ln416_2_fu_544_p2;
wire   [0:0] icmp_ln1494_2_fu_488_p2;
wire   [6:0] select_ln340_2_fu_620_p3;
wire   [6:0] select_ln1494_2_fu_628_p3;
wire   [0:0] tmp_109_fu_664_p3;
wire   [7:0] zext_ln415_37_fu_672_p1;
wire   [7:0] trunc_ln708_2_fu_646_p4;
wire   [6:0] trunc_ln415_3_fu_680_p4;
wire   [6:0] zext_ln415_38_fu_676_p1;
wire   [7:0] add_ln415_18_fu_690_p2;
wire   [0:0] tmp_110_fu_702_p3;
wire   [0:0] tmp_108_fu_656_p3;
wire   [0:0] xor_ln416_3_fu_710_p2;
wire   [4:0] p_Result_12_3_fu_730_p4;
wire   [0:0] and_ln416_3_fu_716_p2;
wire   [0:0] icmp_ln879_3_fu_740_p2;
wire   [0:0] icmp_ln768_3_fu_746_p2;
wire   [0:0] select_ln777_3_fu_752_p3;
wire   [0:0] tmp_111_fu_722_p3;
wire   [0:0] xor_ln785_3_fu_760_p2;
wire   [0:0] or_ln340_3_fu_766_p2;
wire   [6:0] add_ln416_3_fu_696_p2;
wire   [0:0] icmp_ln1494_3_fu_640_p2;
wire   [6:0] select_ln340_3_fu_772_p3;
wire   [6:0] select_ln1494_3_fu_780_p3;
wire   [0:0] tmp_113_fu_816_p3;
wire   [7:0] zext_ln415_39_fu_824_p1;
wire   [7:0] trunc_ln708_3_fu_798_p4;
wire   [6:0] trunc_ln415_4_fu_832_p4;
wire   [6:0] zext_ln415_40_fu_828_p1;
wire   [7:0] add_ln415_19_fu_842_p2;
wire   [0:0] tmp_114_fu_854_p3;
wire   [0:0] tmp_112_fu_808_p3;
wire   [0:0] xor_ln416_4_fu_862_p2;
wire   [4:0] p_Result_12_4_fu_882_p4;
wire   [0:0] and_ln416_4_fu_868_p2;
wire   [0:0] icmp_ln879_4_fu_892_p2;
wire   [0:0] icmp_ln768_4_fu_898_p2;
wire   [0:0] select_ln777_4_fu_904_p3;
wire   [0:0] tmp_115_fu_874_p3;
wire   [0:0] xor_ln785_4_fu_912_p2;
wire   [0:0] or_ln340_4_fu_918_p2;
wire   [6:0] add_ln416_4_fu_848_p2;
wire   [0:0] icmp_ln1494_4_fu_792_p2;
wire   [6:0] select_ln340_4_fu_924_p3;
wire   [6:0] select_ln1494_4_fu_932_p3;
wire   [0:0] tmp_117_fu_968_p3;
wire   [7:0] zext_ln415_41_fu_976_p1;
wire   [7:0] trunc_ln708_4_fu_950_p4;
wire   [6:0] trunc_ln415_5_fu_984_p4;
wire   [6:0] zext_ln415_42_fu_980_p1;
wire   [7:0] add_ln415_20_fu_994_p2;
wire   [0:0] tmp_118_fu_1006_p3;
wire   [0:0] tmp_116_fu_960_p3;
wire   [0:0] xor_ln416_5_fu_1014_p2;
wire   [4:0] p_Result_12_5_fu_1034_p4;
wire   [0:0] and_ln416_5_fu_1020_p2;
wire   [0:0] icmp_ln879_5_fu_1044_p2;
wire   [0:0] icmp_ln768_5_fu_1050_p2;
wire   [0:0] select_ln777_5_fu_1056_p3;
wire   [0:0] tmp_119_fu_1026_p3;
wire   [0:0] xor_ln785_5_fu_1064_p2;
wire   [0:0] or_ln340_5_fu_1070_p2;
wire   [6:0] add_ln416_5_fu_1000_p2;
wire   [0:0] icmp_ln1494_5_fu_944_p2;
wire   [6:0] select_ln340_5_fu_1076_p3;
wire   [6:0] select_ln1494_5_fu_1084_p3;
wire   [0:0] tmp_121_fu_1120_p3;
wire   [7:0] zext_ln415_43_fu_1128_p1;
wire   [7:0] trunc_ln708_5_fu_1102_p4;
wire   [6:0] trunc_ln415_6_fu_1136_p4;
wire   [6:0] zext_ln415_44_fu_1132_p1;
wire   [7:0] add_ln415_21_fu_1146_p2;
wire   [0:0] tmp_122_fu_1158_p3;
wire   [0:0] tmp_120_fu_1112_p3;
wire   [0:0] xor_ln416_6_fu_1166_p2;
wire   [4:0] p_Result_12_6_fu_1186_p4;
wire   [0:0] and_ln416_6_fu_1172_p2;
wire   [0:0] icmp_ln879_6_fu_1196_p2;
wire   [0:0] icmp_ln768_6_fu_1202_p2;
wire   [0:0] select_ln777_6_fu_1208_p3;
wire   [0:0] tmp_123_fu_1178_p3;
wire   [0:0] xor_ln785_6_fu_1216_p2;
wire   [0:0] or_ln340_6_fu_1222_p2;
wire   [6:0] add_ln416_6_fu_1152_p2;
wire   [0:0] icmp_ln1494_6_fu_1096_p2;
wire   [6:0] select_ln340_6_fu_1228_p3;
wire   [6:0] select_ln1494_6_fu_1236_p3;
wire   [0:0] tmp_125_fu_1272_p3;
wire   [7:0] zext_ln415_45_fu_1280_p1;
wire   [7:0] trunc_ln708_6_fu_1254_p4;
wire   [6:0] trunc_ln415_7_fu_1288_p4;
wire   [6:0] zext_ln415_46_fu_1284_p1;
wire   [7:0] add_ln415_22_fu_1298_p2;
wire   [0:0] tmp_126_fu_1310_p3;
wire   [0:0] tmp_124_fu_1264_p3;
wire   [0:0] xor_ln416_7_fu_1318_p2;
wire   [4:0] p_Result_12_7_fu_1338_p4;
wire   [0:0] and_ln416_7_fu_1324_p2;
wire   [0:0] icmp_ln879_7_fu_1348_p2;
wire   [0:0] icmp_ln768_7_fu_1354_p2;
wire   [0:0] select_ln777_7_fu_1360_p3;
wire   [0:0] tmp_127_fu_1330_p3;
wire   [0:0] xor_ln785_7_fu_1368_p2;
wire   [0:0] or_ln340_7_fu_1374_p2;
wire   [6:0] add_ln416_7_fu_1304_p2;
wire   [0:0] icmp_ln1494_7_fu_1248_p2;
wire   [6:0] select_ln340_7_fu_1380_p3;
wire   [6:0] select_ln1494_7_fu_1388_p3;
wire   [0:0] tmp_129_fu_1424_p3;
wire   [7:0] zext_ln415_47_fu_1432_p1;
wire   [7:0] trunc_ln708_7_fu_1406_p4;
wire   [6:0] trunc_ln415_8_fu_1440_p4;
wire   [6:0] zext_ln415_48_fu_1436_p1;
wire   [7:0] add_ln415_23_fu_1450_p2;
wire   [0:0] tmp_130_fu_1462_p3;
wire   [0:0] tmp_128_fu_1416_p3;
wire   [0:0] xor_ln416_8_fu_1470_p2;
wire   [4:0] p_Result_12_8_fu_1490_p4;
wire   [0:0] and_ln416_8_fu_1476_p2;
wire   [0:0] icmp_ln879_8_fu_1500_p2;
wire   [0:0] icmp_ln768_8_fu_1506_p2;
wire   [0:0] select_ln777_8_fu_1512_p3;
wire   [0:0] tmp_131_fu_1482_p3;
wire   [0:0] xor_ln785_8_fu_1520_p2;
wire   [0:0] or_ln340_8_fu_1526_p2;
wire   [6:0] add_ln416_8_fu_1456_p2;
wire   [0:0] icmp_ln1494_8_fu_1400_p2;
wire   [6:0] select_ln340_8_fu_1532_p3;
wire   [6:0] select_ln1494_8_fu_1540_p3;
wire   [0:0] tmp_133_fu_1576_p3;
wire   [7:0] zext_ln415_49_fu_1584_p1;
wire   [7:0] trunc_ln708_8_fu_1558_p4;
wire   [6:0] trunc_ln415_9_fu_1592_p4;
wire   [6:0] zext_ln415_50_fu_1588_p1;
wire   [7:0] add_ln415_24_fu_1602_p2;
wire   [0:0] tmp_134_fu_1614_p3;
wire   [0:0] tmp_132_fu_1568_p3;
wire   [0:0] xor_ln416_9_fu_1622_p2;
wire   [4:0] p_Result_12_9_fu_1642_p4;
wire   [0:0] and_ln416_9_fu_1628_p2;
wire   [0:0] icmp_ln879_9_fu_1652_p2;
wire   [0:0] icmp_ln768_9_fu_1658_p2;
wire   [0:0] select_ln777_9_fu_1664_p3;
wire   [0:0] tmp_135_fu_1634_p3;
wire   [0:0] xor_ln785_9_fu_1672_p2;
wire   [0:0] or_ln340_9_fu_1678_p2;
wire   [6:0] add_ln416_9_fu_1608_p2;
wire   [0:0] icmp_ln1494_9_fu_1552_p2;
wire   [6:0] select_ln340_9_fu_1684_p3;
wire   [6:0] select_ln1494_9_fu_1692_p3;
wire   [0:0] tmp_137_fu_1728_p3;
wire   [7:0] zext_ln415_51_fu_1736_p1;
wire   [7:0] trunc_ln708_9_fu_1710_p4;
wire   [6:0] trunc_ln415_10_fu_1744_p4;
wire   [6:0] zext_ln415_52_fu_1740_p1;
wire   [7:0] add_ln415_25_fu_1754_p2;
wire   [0:0] tmp_138_fu_1766_p3;
wire   [0:0] tmp_136_fu_1720_p3;
wire   [0:0] xor_ln416_10_fu_1774_p2;
wire   [4:0] p_Result_12_s_fu_1794_p4;
wire   [0:0] and_ln416_10_fu_1780_p2;
wire   [0:0] icmp_ln879_10_fu_1804_p2;
wire   [0:0] icmp_ln768_10_fu_1810_p2;
wire   [0:0] select_ln777_10_fu_1816_p3;
wire   [0:0] tmp_139_fu_1786_p3;
wire   [0:0] xor_ln785_10_fu_1824_p2;
wire   [0:0] or_ln340_10_fu_1830_p2;
wire   [6:0] add_ln416_10_fu_1760_p2;
wire   [0:0] icmp_ln1494_10_fu_1704_p2;
wire   [6:0] select_ln340_10_fu_1836_p3;
wire   [6:0] select_ln1494_10_fu_1844_p3;
wire   [0:0] tmp_141_fu_1880_p3;
wire   [7:0] zext_ln415_53_fu_1888_p1;
wire   [7:0] trunc_ln708_10_fu_1862_p4;
wire   [6:0] trunc_ln415_11_fu_1896_p4;
wire   [6:0] zext_ln415_54_fu_1892_p1;
wire   [7:0] add_ln415_26_fu_1906_p2;
wire   [0:0] tmp_142_fu_1918_p3;
wire   [0:0] tmp_140_fu_1872_p3;
wire   [0:0] xor_ln416_11_fu_1926_p2;
wire   [4:0] p_Result_12_10_fu_1946_p4;
wire   [0:0] and_ln416_11_fu_1932_p2;
wire   [0:0] icmp_ln879_11_fu_1956_p2;
wire   [0:0] icmp_ln768_11_fu_1962_p2;
wire   [0:0] select_ln777_11_fu_1968_p3;
wire   [0:0] tmp_143_fu_1938_p3;
wire   [0:0] xor_ln785_11_fu_1976_p2;
wire   [0:0] or_ln340_11_fu_1982_p2;
wire   [6:0] add_ln416_11_fu_1912_p2;
wire   [0:0] icmp_ln1494_11_fu_1856_p2;
wire   [6:0] select_ln340_11_fu_1988_p3;
wire   [6:0] select_ln1494_11_fu_1996_p3;
wire   [0:0] tmp_145_fu_2032_p3;
wire   [7:0] zext_ln415_55_fu_2040_p1;
wire   [7:0] trunc_ln708_11_fu_2014_p4;
wire   [6:0] trunc_ln415_12_fu_2048_p4;
wire   [6:0] zext_ln415_56_fu_2044_p1;
wire   [7:0] add_ln415_27_fu_2058_p2;
wire   [0:0] tmp_146_fu_2070_p3;
wire   [0:0] tmp_144_fu_2024_p3;
wire   [0:0] xor_ln416_12_fu_2078_p2;
wire   [4:0] p_Result_12_11_fu_2098_p4;
wire   [0:0] and_ln416_12_fu_2084_p2;
wire   [0:0] icmp_ln879_12_fu_2108_p2;
wire   [0:0] icmp_ln768_12_fu_2114_p2;
wire   [0:0] select_ln777_12_fu_2120_p3;
wire   [0:0] tmp_147_fu_2090_p3;
wire   [0:0] xor_ln785_12_fu_2128_p2;
wire   [0:0] or_ln340_12_fu_2134_p2;
wire   [6:0] add_ln416_12_fu_2064_p2;
wire   [0:0] icmp_ln1494_12_fu_2008_p2;
wire   [6:0] select_ln340_12_fu_2140_p3;
wire   [6:0] select_ln1494_12_fu_2148_p3;
wire   [0:0] tmp_149_fu_2184_p3;
wire   [7:0] zext_ln415_57_fu_2192_p1;
wire   [7:0] trunc_ln708_12_fu_2166_p4;
wire   [6:0] trunc_ln415_13_fu_2200_p4;
wire   [6:0] zext_ln415_58_fu_2196_p1;
wire   [7:0] add_ln415_28_fu_2210_p2;
wire   [0:0] tmp_150_fu_2222_p3;
wire   [0:0] tmp_148_fu_2176_p3;
wire   [0:0] xor_ln416_13_fu_2230_p2;
wire   [4:0] p_Result_12_12_fu_2250_p4;
wire   [0:0] and_ln416_13_fu_2236_p2;
wire   [0:0] icmp_ln879_13_fu_2260_p2;
wire   [0:0] icmp_ln768_13_fu_2266_p2;
wire   [0:0] select_ln777_13_fu_2272_p3;
wire   [0:0] tmp_151_fu_2242_p3;
wire   [0:0] xor_ln785_13_fu_2280_p2;
wire   [0:0] or_ln340_13_fu_2286_p2;
wire   [6:0] add_ln416_13_fu_2216_p2;
wire   [0:0] icmp_ln1494_13_fu_2160_p2;
wire   [6:0] select_ln340_13_fu_2292_p3;
wire   [6:0] select_ln1494_13_fu_2300_p3;
wire   [0:0] tmp_153_fu_2336_p3;
wire   [7:0] zext_ln415_59_fu_2344_p1;
wire   [7:0] trunc_ln708_13_fu_2318_p4;
wire   [6:0] trunc_ln415_14_fu_2352_p4;
wire   [6:0] zext_ln415_60_fu_2348_p1;
wire   [7:0] add_ln415_29_fu_2362_p2;
wire   [0:0] tmp_154_fu_2374_p3;
wire   [0:0] tmp_152_fu_2328_p3;
wire   [0:0] xor_ln416_14_fu_2382_p2;
wire   [4:0] p_Result_12_13_fu_2402_p4;
wire   [0:0] and_ln416_14_fu_2388_p2;
wire   [0:0] icmp_ln879_14_fu_2412_p2;
wire   [0:0] icmp_ln768_14_fu_2418_p2;
wire   [0:0] select_ln777_14_fu_2424_p3;
wire   [0:0] tmp_155_fu_2394_p3;
wire   [0:0] xor_ln785_14_fu_2432_p2;
wire   [0:0] or_ln340_14_fu_2438_p2;
wire   [6:0] add_ln416_14_fu_2368_p2;
wire   [0:0] icmp_ln1494_14_fu_2312_p2;
wire   [6:0] select_ln340_14_fu_2444_p3;
wire   [6:0] select_ln1494_14_fu_2452_p3;
wire   [0:0] tmp_157_fu_2488_p3;
wire   [7:0] zext_ln415_61_fu_2496_p1;
wire   [7:0] trunc_ln708_14_fu_2470_p4;
wire   [6:0] trunc_ln415_15_fu_2504_p4;
wire   [6:0] zext_ln415_62_fu_2500_p1;
wire   [7:0] add_ln415_30_fu_2514_p2;
wire   [0:0] tmp_158_fu_2526_p3;
wire   [0:0] tmp_156_fu_2480_p3;
wire   [0:0] xor_ln416_15_fu_2534_p2;
wire   [4:0] p_Result_12_14_fu_2554_p4;
wire   [0:0] and_ln416_15_fu_2540_p2;
wire   [0:0] icmp_ln879_15_fu_2564_p2;
wire   [0:0] icmp_ln768_15_fu_2570_p2;
wire   [0:0] select_ln777_15_fu_2576_p3;
wire   [0:0] tmp_159_fu_2546_p3;
wire   [0:0] xor_ln785_15_fu_2584_p2;
wire   [0:0] or_ln340_15_fu_2590_p2;
wire   [6:0] add_ln416_15_fu_2520_p2;
wire   [0:0] icmp_ln1494_15_fu_2464_p2;
wire   [6:0] select_ln340_15_fu_2596_p3;
wire   [6:0] select_ln1494_15_fu_2604_p3;
wire   [7:0] zext_ln1494_fu_332_p1;
wire   [7:0] zext_ln1494_1_fu_484_p1;
wire   [7:0] zext_ln1494_2_fu_636_p1;
wire   [7:0] zext_ln1494_3_fu_788_p1;
wire   [7:0] zext_ln1494_4_fu_940_p1;
wire   [7:0] zext_ln1494_5_fu_1092_p1;
wire   [7:0] zext_ln1494_6_fu_1244_p1;
wire   [7:0] zext_ln1494_7_fu_1396_p1;
wire   [7:0] zext_ln1494_8_fu_1548_p1;
wire   [7:0] zext_ln1494_9_fu_1700_p1;
wire   [7:0] zext_ln1494_10_fu_1852_p1;
wire   [7:0] zext_ln1494_11_fu_2004_p1;
wire   [7:0] zext_ln1494_12_fu_2156_p1;
wire   [7:0] zext_ln1494_13_fu_2308_p1;
wire   [7:0] zext_ln1494_14_fu_2460_p1;
wire   [7:0] zext_ln1494_15_fu_2612_p1;

assign add_ln415_16_fu_386_p2 = (zext_ln415_33_fu_368_p1 + trunc_ln708_s_fu_342_p4);

assign add_ln415_17_fu_538_p2 = (zext_ln415_35_fu_520_p1 + trunc_ln708_1_fu_494_p4);

assign add_ln415_18_fu_690_p2 = (zext_ln415_37_fu_672_p1 + trunc_ln708_2_fu_646_p4);

assign add_ln415_19_fu_842_p2 = (zext_ln415_39_fu_824_p1 + trunc_ln708_3_fu_798_p4);

assign add_ln415_20_fu_994_p2 = (zext_ln415_41_fu_976_p1 + trunc_ln708_4_fu_950_p4);

assign add_ln415_21_fu_1146_p2 = (zext_ln415_43_fu_1128_p1 + trunc_ln708_5_fu_1102_p4);

assign add_ln415_22_fu_1298_p2 = (zext_ln415_45_fu_1280_p1 + trunc_ln708_6_fu_1254_p4);

assign add_ln415_23_fu_1450_p2 = (zext_ln415_47_fu_1432_p1 + trunc_ln708_7_fu_1406_p4);

assign add_ln415_24_fu_1602_p2 = (zext_ln415_49_fu_1584_p1 + trunc_ln708_8_fu_1558_p4);

assign add_ln415_25_fu_1754_p2 = (zext_ln415_51_fu_1736_p1 + trunc_ln708_9_fu_1710_p4);

assign add_ln415_26_fu_1906_p2 = (zext_ln415_53_fu_1888_p1 + trunc_ln708_10_fu_1862_p4);

assign add_ln415_27_fu_2058_p2 = (zext_ln415_55_fu_2040_p1 + trunc_ln708_11_fu_2014_p4);

assign add_ln415_28_fu_2210_p2 = (zext_ln415_57_fu_2192_p1 + trunc_ln708_12_fu_2166_p4);

assign add_ln415_29_fu_2362_p2 = (zext_ln415_59_fu_2344_p1 + trunc_ln708_13_fu_2318_p4);

assign add_ln415_30_fu_2514_p2 = (zext_ln415_61_fu_2496_p1 + trunc_ln708_14_fu_2470_p4);

assign add_ln415_fu_234_p2 = (zext_ln415_fu_216_p1 + trunc_ln_fu_190_p4);

assign add_ln416_10_fu_1760_p2 = (trunc_ln415_10_fu_1744_p4 + zext_ln415_52_fu_1740_p1);

assign add_ln416_11_fu_1912_p2 = (trunc_ln415_11_fu_1896_p4 + zext_ln415_54_fu_1892_p1);

assign add_ln416_12_fu_2064_p2 = (trunc_ln415_12_fu_2048_p4 + zext_ln415_56_fu_2044_p1);

assign add_ln416_13_fu_2216_p2 = (trunc_ln415_13_fu_2200_p4 + zext_ln415_58_fu_2196_p1);

assign add_ln416_14_fu_2368_p2 = (trunc_ln415_14_fu_2352_p4 + zext_ln415_60_fu_2348_p1);

assign add_ln416_15_fu_2520_p2 = (trunc_ln415_15_fu_2504_p4 + zext_ln415_62_fu_2500_p1);

assign add_ln416_1_fu_392_p2 = (trunc_ln415_1_fu_376_p4 + zext_ln415_34_fu_372_p1);

assign add_ln416_2_fu_544_p2 = (trunc_ln415_2_fu_528_p4 + zext_ln415_36_fu_524_p1);

assign add_ln416_3_fu_696_p2 = (trunc_ln415_3_fu_680_p4 + zext_ln415_38_fu_676_p1);

assign add_ln416_4_fu_848_p2 = (trunc_ln415_4_fu_832_p4 + zext_ln415_40_fu_828_p1);

assign add_ln416_5_fu_1000_p2 = (trunc_ln415_5_fu_984_p4 + zext_ln415_42_fu_980_p1);

assign add_ln416_6_fu_1152_p2 = (trunc_ln415_6_fu_1136_p4 + zext_ln415_44_fu_1132_p1);

assign add_ln416_7_fu_1304_p2 = (trunc_ln415_7_fu_1288_p4 + zext_ln415_46_fu_1284_p1);

assign add_ln416_8_fu_1456_p2 = (trunc_ln415_8_fu_1440_p4 + zext_ln415_48_fu_1436_p1);

assign add_ln416_9_fu_1608_p2 = (trunc_ln415_9_fu_1592_p4 + zext_ln415_50_fu_1588_p1);

assign add_ln416_fu_240_p2 = (trunc_ln415_s_fu_224_p4 + zext_ln415_32_fu_220_p1);

assign and_ln416_10_fu_1780_p2 = (xor_ln416_10_fu_1774_p2 & tmp_136_fu_1720_p3);

assign and_ln416_11_fu_1932_p2 = (xor_ln416_11_fu_1926_p2 & tmp_140_fu_1872_p3);

assign and_ln416_12_fu_2084_p2 = (xor_ln416_12_fu_2078_p2 & tmp_144_fu_2024_p3);

assign and_ln416_13_fu_2236_p2 = (xor_ln416_13_fu_2230_p2 & tmp_148_fu_2176_p3);

assign and_ln416_14_fu_2388_p2 = (xor_ln416_14_fu_2382_p2 & tmp_152_fu_2328_p3);

assign and_ln416_15_fu_2540_p2 = (xor_ln416_15_fu_2534_p2 & tmp_156_fu_2480_p3);

assign and_ln416_1_fu_412_p2 = (xor_ln416_1_fu_406_p2 & tmp_100_fu_352_p3);

assign and_ln416_2_fu_564_p2 = (xor_ln416_2_fu_558_p2 & tmp_104_fu_504_p3);

assign and_ln416_3_fu_716_p2 = (xor_ln416_3_fu_710_p2 & tmp_108_fu_656_p3);

assign and_ln416_4_fu_868_p2 = (xor_ln416_4_fu_862_p2 & tmp_112_fu_808_p3);

assign and_ln416_5_fu_1020_p2 = (xor_ln416_5_fu_1014_p2 & tmp_116_fu_960_p3);

assign and_ln416_6_fu_1172_p2 = (xor_ln416_6_fu_1166_p2 & tmp_120_fu_1112_p3);

assign and_ln416_7_fu_1324_p2 = (xor_ln416_7_fu_1318_p2 & tmp_124_fu_1264_p3);

assign and_ln416_8_fu_1476_p2 = (xor_ln416_8_fu_1470_p2 & tmp_128_fu_1416_p3);

assign and_ln416_9_fu_1628_p2 = (xor_ln416_9_fu_1622_p2 & tmp_132_fu_1568_p3);

assign and_ln416_fu_260_p2 = (xor_ln416_fu_254_p2 & tmp_96_fu_200_p3);

assign ap_ready = 1'b1;

assign ap_return_0 = zext_ln1494_fu_332_p1;

assign ap_return_1 = zext_ln1494_1_fu_484_p1;

assign ap_return_10 = zext_ln1494_10_fu_1852_p1;

assign ap_return_11 = zext_ln1494_11_fu_2004_p1;

assign ap_return_12 = zext_ln1494_12_fu_2156_p1;

assign ap_return_13 = zext_ln1494_13_fu_2308_p1;

assign ap_return_14 = zext_ln1494_14_fu_2460_p1;

assign ap_return_15 = zext_ln1494_15_fu_2612_p1;

assign ap_return_2 = zext_ln1494_2_fu_636_p1;

assign ap_return_3 = zext_ln1494_3_fu_788_p1;

assign ap_return_4 = zext_ln1494_4_fu_940_p1;

assign ap_return_5 = zext_ln1494_5_fu_1092_p1;

assign ap_return_6 = zext_ln1494_6_fu_1244_p1;

assign ap_return_7 = zext_ln1494_7_fu_1396_p1;

assign ap_return_8 = zext_ln1494_8_fu_1548_p1;

assign ap_return_9 = zext_ln1494_9_fu_1700_p1;

assign icmp_ln1494_10_fu_1704_p2 = (($signed(data_10_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1856_p2 = (($signed(data_11_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_2008_p2 = (($signed(data_12_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_2160_p2 = (($signed(data_13_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_2312_p2 = (($signed(data_14_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_2464_p2 = (($signed(data_15_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_336_p2 = (($signed(data_1_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_488_p2 = (($signed(data_2_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_640_p2 = (($signed(data_3_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_792_p2 = (($signed(data_4_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_944_p2 = (($signed(data_5_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1096_p2 = (($signed(data_6_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1248_p2 = (($signed(data_7_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1400_p2 = (($signed(data_8_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1552_p2 = (($signed(data_9_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_184_p2 = (($signed(data_0_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln768_10_fu_1810_p2 = ((p_Result_12_s_fu_1794_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_11_fu_1962_p2 = ((p_Result_12_10_fu_1946_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_12_fu_2114_p2 = ((p_Result_12_11_fu_2098_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_13_fu_2266_p2 = ((p_Result_12_12_fu_2250_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_14_fu_2418_p2 = ((p_Result_12_13_fu_2402_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_15_fu_2570_p2 = ((p_Result_12_14_fu_2554_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_1_fu_442_p2 = ((p_Result_12_1_fu_426_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_2_fu_594_p2 = ((p_Result_12_2_fu_578_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_3_fu_746_p2 = ((p_Result_12_3_fu_730_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_4_fu_898_p2 = ((p_Result_12_4_fu_882_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_5_fu_1050_p2 = ((p_Result_12_5_fu_1034_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_6_fu_1202_p2 = ((p_Result_12_6_fu_1186_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_7_fu_1354_p2 = ((p_Result_12_7_fu_1338_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_8_fu_1506_p2 = ((p_Result_12_8_fu_1490_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_9_fu_1658_p2 = ((p_Result_12_9_fu_1642_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_fu_290_p2 = ((p_Result_s_fu_274_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_10_fu_1804_p2 = ((p_Result_12_s_fu_1794_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_11_fu_1956_p2 = ((p_Result_12_10_fu_1946_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_12_fu_2108_p2 = ((p_Result_12_11_fu_2098_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_13_fu_2260_p2 = ((p_Result_12_12_fu_2250_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_14_fu_2412_p2 = ((p_Result_12_13_fu_2402_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_15_fu_2564_p2 = ((p_Result_12_14_fu_2554_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_436_p2 = ((p_Result_12_1_fu_426_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_588_p2 = ((p_Result_12_2_fu_578_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_3_fu_740_p2 = ((p_Result_12_3_fu_730_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_4_fu_892_p2 = ((p_Result_12_4_fu_882_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_5_fu_1044_p2 = ((p_Result_12_5_fu_1034_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_6_fu_1196_p2 = ((p_Result_12_6_fu_1186_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_7_fu_1348_p2 = ((p_Result_12_7_fu_1338_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_8_fu_1500_p2 = ((p_Result_12_8_fu_1490_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_9_fu_1652_p2 = ((p_Result_12_9_fu_1642_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_284_p2 = ((p_Result_s_fu_274_p4 == 5'd31) ? 1'b1 : 1'b0);

assign or_ln340_10_fu_1830_p2 = (xor_ln785_10_fu_1824_p2 | tmp_139_fu_1786_p3);

assign or_ln340_11_fu_1982_p2 = (xor_ln785_11_fu_1976_p2 | tmp_143_fu_1938_p3);

assign or_ln340_12_fu_2134_p2 = (xor_ln785_12_fu_2128_p2 | tmp_147_fu_2090_p3);

assign or_ln340_13_fu_2286_p2 = (xor_ln785_13_fu_2280_p2 | tmp_151_fu_2242_p3);

assign or_ln340_14_fu_2438_p2 = (xor_ln785_14_fu_2432_p2 | tmp_155_fu_2394_p3);

assign or_ln340_15_fu_2590_p2 = (xor_ln785_15_fu_2584_p2 | tmp_159_fu_2546_p3);

assign or_ln340_1_fu_462_p2 = (xor_ln785_1_fu_456_p2 | tmp_103_fu_418_p3);

assign or_ln340_2_fu_614_p2 = (xor_ln785_2_fu_608_p2 | tmp_107_fu_570_p3);

assign or_ln340_3_fu_766_p2 = (xor_ln785_3_fu_760_p2 | tmp_111_fu_722_p3);

assign or_ln340_4_fu_918_p2 = (xor_ln785_4_fu_912_p2 | tmp_115_fu_874_p3);

assign or_ln340_5_fu_1070_p2 = (xor_ln785_5_fu_1064_p2 | tmp_119_fu_1026_p3);

assign or_ln340_6_fu_1222_p2 = (xor_ln785_6_fu_1216_p2 | tmp_123_fu_1178_p3);

assign or_ln340_7_fu_1374_p2 = (xor_ln785_7_fu_1368_p2 | tmp_127_fu_1330_p3);

assign or_ln340_8_fu_1526_p2 = (xor_ln785_8_fu_1520_p2 | tmp_131_fu_1482_p3);

assign or_ln340_9_fu_1678_p2 = (xor_ln785_9_fu_1672_p2 | tmp_135_fu_1634_p3);

assign or_ln340_fu_310_p2 = (xor_ln785_fu_304_p2 | tmp_99_fu_266_p3);

assign p_Result_12_10_fu_1946_p4 = {{data_11_V_read[15:11]}};

assign p_Result_12_11_fu_2098_p4 = {{data_12_V_read[15:11]}};

assign p_Result_12_12_fu_2250_p4 = {{data_13_V_read[15:11]}};

assign p_Result_12_13_fu_2402_p4 = {{data_14_V_read[15:11]}};

assign p_Result_12_14_fu_2554_p4 = {{data_15_V_read[15:11]}};

assign p_Result_12_1_fu_426_p4 = {{data_1_V_read[15:11]}};

assign p_Result_12_2_fu_578_p4 = {{data_2_V_read[15:11]}};

assign p_Result_12_3_fu_730_p4 = {{data_3_V_read[15:11]}};

assign p_Result_12_4_fu_882_p4 = {{data_4_V_read[15:11]}};

assign p_Result_12_5_fu_1034_p4 = {{data_5_V_read[15:11]}};

assign p_Result_12_6_fu_1186_p4 = {{data_6_V_read[15:11]}};

assign p_Result_12_7_fu_1338_p4 = {{data_7_V_read[15:11]}};

assign p_Result_12_8_fu_1490_p4 = {{data_8_V_read[15:11]}};

assign p_Result_12_9_fu_1642_p4 = {{data_9_V_read[15:11]}};

assign p_Result_12_s_fu_1794_p4 = {{data_10_V_read[15:11]}};

assign p_Result_s_fu_274_p4 = {{data_0_V_read[15:11]}};

assign select_ln1494_10_fu_1844_p3 = ((icmp_ln1494_10_fu_1704_p2[0:0] === 1'b1) ? select_ln340_10_fu_1836_p3 : 7'd0);

assign select_ln1494_11_fu_1996_p3 = ((icmp_ln1494_11_fu_1856_p2[0:0] === 1'b1) ? select_ln340_11_fu_1988_p3 : 7'd0);

assign select_ln1494_12_fu_2148_p3 = ((icmp_ln1494_12_fu_2008_p2[0:0] === 1'b1) ? select_ln340_12_fu_2140_p3 : 7'd0);

assign select_ln1494_13_fu_2300_p3 = ((icmp_ln1494_13_fu_2160_p2[0:0] === 1'b1) ? select_ln340_13_fu_2292_p3 : 7'd0);

assign select_ln1494_14_fu_2452_p3 = ((icmp_ln1494_14_fu_2312_p2[0:0] === 1'b1) ? select_ln340_14_fu_2444_p3 : 7'd0);

assign select_ln1494_15_fu_2604_p3 = ((icmp_ln1494_15_fu_2464_p2[0:0] === 1'b1) ? select_ln340_15_fu_2596_p3 : 7'd0);

assign select_ln1494_1_fu_476_p3 = ((icmp_ln1494_1_fu_336_p2[0:0] === 1'b1) ? select_ln340_1_fu_468_p3 : 7'd0);

assign select_ln1494_2_fu_628_p3 = ((icmp_ln1494_2_fu_488_p2[0:0] === 1'b1) ? select_ln340_2_fu_620_p3 : 7'd0);

assign select_ln1494_3_fu_780_p3 = ((icmp_ln1494_3_fu_640_p2[0:0] === 1'b1) ? select_ln340_3_fu_772_p3 : 7'd0);

assign select_ln1494_4_fu_932_p3 = ((icmp_ln1494_4_fu_792_p2[0:0] === 1'b1) ? select_ln340_4_fu_924_p3 : 7'd0);

assign select_ln1494_5_fu_1084_p3 = ((icmp_ln1494_5_fu_944_p2[0:0] === 1'b1) ? select_ln340_5_fu_1076_p3 : 7'd0);

assign select_ln1494_6_fu_1236_p3 = ((icmp_ln1494_6_fu_1096_p2[0:0] === 1'b1) ? select_ln340_6_fu_1228_p3 : 7'd0);

assign select_ln1494_7_fu_1388_p3 = ((icmp_ln1494_7_fu_1248_p2[0:0] === 1'b1) ? select_ln340_7_fu_1380_p3 : 7'd0);

assign select_ln1494_8_fu_1540_p3 = ((icmp_ln1494_8_fu_1400_p2[0:0] === 1'b1) ? select_ln340_8_fu_1532_p3 : 7'd0);

assign select_ln1494_9_fu_1692_p3 = ((icmp_ln1494_9_fu_1552_p2[0:0] === 1'b1) ? select_ln340_9_fu_1684_p3 : 7'd0);

assign select_ln1494_fu_324_p3 = ((icmp_ln1494_fu_184_p2[0:0] === 1'b1) ? select_ln340_fu_316_p3 : 7'd0);

assign select_ln340_10_fu_1836_p3 = ((or_ln340_10_fu_1830_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_10_fu_1760_p2);

assign select_ln340_11_fu_1988_p3 = ((or_ln340_11_fu_1982_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_11_fu_1912_p2);

assign select_ln340_12_fu_2140_p3 = ((or_ln340_12_fu_2134_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_12_fu_2064_p2);

assign select_ln340_13_fu_2292_p3 = ((or_ln340_13_fu_2286_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_13_fu_2216_p2);

assign select_ln340_14_fu_2444_p3 = ((or_ln340_14_fu_2438_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_14_fu_2368_p2);

assign select_ln340_15_fu_2596_p3 = ((or_ln340_15_fu_2590_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_15_fu_2520_p2);

assign select_ln340_1_fu_468_p3 = ((or_ln340_1_fu_462_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_1_fu_392_p2);

assign select_ln340_2_fu_620_p3 = ((or_ln340_2_fu_614_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_2_fu_544_p2);

assign select_ln340_3_fu_772_p3 = ((or_ln340_3_fu_766_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_3_fu_696_p2);

assign select_ln340_4_fu_924_p3 = ((or_ln340_4_fu_918_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_4_fu_848_p2);

assign select_ln340_5_fu_1076_p3 = ((or_ln340_5_fu_1070_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_5_fu_1000_p2);

assign select_ln340_6_fu_1228_p3 = ((or_ln340_6_fu_1222_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_6_fu_1152_p2);

assign select_ln340_7_fu_1380_p3 = ((or_ln340_7_fu_1374_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_7_fu_1304_p2);

assign select_ln340_8_fu_1532_p3 = ((or_ln340_8_fu_1526_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_8_fu_1456_p2);

assign select_ln340_9_fu_1684_p3 = ((or_ln340_9_fu_1678_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_9_fu_1608_p2);

assign select_ln340_fu_316_p3 = ((or_ln340_fu_310_p2[0:0] === 1'b1) ? 7'd127 : add_ln416_fu_240_p2);

assign select_ln777_10_fu_1816_p3 = ((and_ln416_10_fu_1780_p2[0:0] === 1'b1) ? icmp_ln879_10_fu_1804_p2 : icmp_ln768_10_fu_1810_p2);

assign select_ln777_11_fu_1968_p3 = ((and_ln416_11_fu_1932_p2[0:0] === 1'b1) ? icmp_ln879_11_fu_1956_p2 : icmp_ln768_11_fu_1962_p2);

assign select_ln777_12_fu_2120_p3 = ((and_ln416_12_fu_2084_p2[0:0] === 1'b1) ? icmp_ln879_12_fu_2108_p2 : icmp_ln768_12_fu_2114_p2);

assign select_ln777_13_fu_2272_p3 = ((and_ln416_13_fu_2236_p2[0:0] === 1'b1) ? icmp_ln879_13_fu_2260_p2 : icmp_ln768_13_fu_2266_p2);

assign select_ln777_14_fu_2424_p3 = ((and_ln416_14_fu_2388_p2[0:0] === 1'b1) ? icmp_ln879_14_fu_2412_p2 : icmp_ln768_14_fu_2418_p2);

assign select_ln777_15_fu_2576_p3 = ((and_ln416_15_fu_2540_p2[0:0] === 1'b1) ? icmp_ln879_15_fu_2564_p2 : icmp_ln768_15_fu_2570_p2);

assign select_ln777_1_fu_448_p3 = ((and_ln416_1_fu_412_p2[0:0] === 1'b1) ? icmp_ln879_1_fu_436_p2 : icmp_ln768_1_fu_442_p2);

assign select_ln777_2_fu_600_p3 = ((and_ln416_2_fu_564_p2[0:0] === 1'b1) ? icmp_ln879_2_fu_588_p2 : icmp_ln768_2_fu_594_p2);

assign select_ln777_3_fu_752_p3 = ((and_ln416_3_fu_716_p2[0:0] === 1'b1) ? icmp_ln879_3_fu_740_p2 : icmp_ln768_3_fu_746_p2);

assign select_ln777_4_fu_904_p3 = ((and_ln416_4_fu_868_p2[0:0] === 1'b1) ? icmp_ln879_4_fu_892_p2 : icmp_ln768_4_fu_898_p2);

assign select_ln777_5_fu_1056_p3 = ((and_ln416_5_fu_1020_p2[0:0] === 1'b1) ? icmp_ln879_5_fu_1044_p2 : icmp_ln768_5_fu_1050_p2);

assign select_ln777_6_fu_1208_p3 = ((and_ln416_6_fu_1172_p2[0:0] === 1'b1) ? icmp_ln879_6_fu_1196_p2 : icmp_ln768_6_fu_1202_p2);

assign select_ln777_7_fu_1360_p3 = ((and_ln416_7_fu_1324_p2[0:0] === 1'b1) ? icmp_ln879_7_fu_1348_p2 : icmp_ln768_7_fu_1354_p2);

assign select_ln777_8_fu_1512_p3 = ((and_ln416_8_fu_1476_p2[0:0] === 1'b1) ? icmp_ln879_8_fu_1500_p2 : icmp_ln768_8_fu_1506_p2);

assign select_ln777_9_fu_1664_p3 = ((and_ln416_9_fu_1628_p2[0:0] === 1'b1) ? icmp_ln879_9_fu_1652_p2 : icmp_ln768_9_fu_1658_p2);

assign select_ln777_fu_296_p3 = ((and_ln416_fu_260_p2[0:0] === 1'b1) ? icmp_ln879_fu_284_p2 : icmp_ln768_fu_290_p2);

assign tmp_100_fu_352_p3 = data_1_V_read[32'd10];

assign tmp_101_fu_360_p3 = data_1_V_read[32'd2];

assign tmp_102_fu_398_p3 = add_ln415_16_fu_386_p2[32'd7];

assign tmp_103_fu_418_p3 = add_ln415_16_fu_386_p2[32'd7];

assign tmp_104_fu_504_p3 = data_2_V_read[32'd10];

assign tmp_105_fu_512_p3 = data_2_V_read[32'd2];

assign tmp_106_fu_550_p3 = add_ln415_17_fu_538_p2[32'd7];

assign tmp_107_fu_570_p3 = add_ln415_17_fu_538_p2[32'd7];

assign tmp_108_fu_656_p3 = data_3_V_read[32'd10];

assign tmp_109_fu_664_p3 = data_3_V_read[32'd2];

assign tmp_110_fu_702_p3 = add_ln415_18_fu_690_p2[32'd7];

assign tmp_111_fu_722_p3 = add_ln415_18_fu_690_p2[32'd7];

assign tmp_112_fu_808_p3 = data_4_V_read[32'd10];

assign tmp_113_fu_816_p3 = data_4_V_read[32'd2];

assign tmp_114_fu_854_p3 = add_ln415_19_fu_842_p2[32'd7];

assign tmp_115_fu_874_p3 = add_ln415_19_fu_842_p2[32'd7];

assign tmp_116_fu_960_p3 = data_5_V_read[32'd10];

assign tmp_117_fu_968_p3 = data_5_V_read[32'd2];

assign tmp_118_fu_1006_p3 = add_ln415_20_fu_994_p2[32'd7];

assign tmp_119_fu_1026_p3 = add_ln415_20_fu_994_p2[32'd7];

assign tmp_120_fu_1112_p3 = data_6_V_read[32'd10];

assign tmp_121_fu_1120_p3 = data_6_V_read[32'd2];

assign tmp_122_fu_1158_p3 = add_ln415_21_fu_1146_p2[32'd7];

assign tmp_123_fu_1178_p3 = add_ln415_21_fu_1146_p2[32'd7];

assign tmp_124_fu_1264_p3 = data_7_V_read[32'd10];

assign tmp_125_fu_1272_p3 = data_7_V_read[32'd2];

assign tmp_126_fu_1310_p3 = add_ln415_22_fu_1298_p2[32'd7];

assign tmp_127_fu_1330_p3 = add_ln415_22_fu_1298_p2[32'd7];

assign tmp_128_fu_1416_p3 = data_8_V_read[32'd10];

assign tmp_129_fu_1424_p3 = data_8_V_read[32'd2];

assign tmp_130_fu_1462_p3 = add_ln415_23_fu_1450_p2[32'd7];

assign tmp_131_fu_1482_p3 = add_ln415_23_fu_1450_p2[32'd7];

assign tmp_132_fu_1568_p3 = data_9_V_read[32'd10];

assign tmp_133_fu_1576_p3 = data_9_V_read[32'd2];

assign tmp_134_fu_1614_p3 = add_ln415_24_fu_1602_p2[32'd7];

assign tmp_135_fu_1634_p3 = add_ln415_24_fu_1602_p2[32'd7];

assign tmp_136_fu_1720_p3 = data_10_V_read[32'd10];

assign tmp_137_fu_1728_p3 = data_10_V_read[32'd2];

assign tmp_138_fu_1766_p3 = add_ln415_25_fu_1754_p2[32'd7];

assign tmp_139_fu_1786_p3 = add_ln415_25_fu_1754_p2[32'd7];

assign tmp_140_fu_1872_p3 = data_11_V_read[32'd10];

assign tmp_141_fu_1880_p3 = data_11_V_read[32'd2];

assign tmp_142_fu_1918_p3 = add_ln415_26_fu_1906_p2[32'd7];

assign tmp_143_fu_1938_p3 = add_ln415_26_fu_1906_p2[32'd7];

assign tmp_144_fu_2024_p3 = data_12_V_read[32'd10];

assign tmp_145_fu_2032_p3 = data_12_V_read[32'd2];

assign tmp_146_fu_2070_p3 = add_ln415_27_fu_2058_p2[32'd7];

assign tmp_147_fu_2090_p3 = add_ln415_27_fu_2058_p2[32'd7];

assign tmp_148_fu_2176_p3 = data_13_V_read[32'd10];

assign tmp_149_fu_2184_p3 = data_13_V_read[32'd2];

assign tmp_150_fu_2222_p3 = add_ln415_28_fu_2210_p2[32'd7];

assign tmp_151_fu_2242_p3 = add_ln415_28_fu_2210_p2[32'd7];

assign tmp_152_fu_2328_p3 = data_14_V_read[32'd10];

assign tmp_153_fu_2336_p3 = data_14_V_read[32'd2];

assign tmp_154_fu_2374_p3 = add_ln415_29_fu_2362_p2[32'd7];

assign tmp_155_fu_2394_p3 = add_ln415_29_fu_2362_p2[32'd7];

assign tmp_156_fu_2480_p3 = data_15_V_read[32'd10];

assign tmp_157_fu_2488_p3 = data_15_V_read[32'd2];

assign tmp_158_fu_2526_p3 = add_ln415_30_fu_2514_p2[32'd7];

assign tmp_159_fu_2546_p3 = add_ln415_30_fu_2514_p2[32'd7];

assign tmp_96_fu_200_p3 = data_0_V_read[32'd10];

assign tmp_97_fu_208_p3 = data_0_V_read[32'd2];

assign tmp_98_fu_246_p3 = add_ln415_fu_234_p2[32'd7];

assign tmp_99_fu_266_p3 = add_ln415_fu_234_p2[32'd7];

assign trunc_ln415_10_fu_1744_p4 = {{data_10_V_read[9:3]}};

assign trunc_ln415_11_fu_1896_p4 = {{data_11_V_read[9:3]}};

assign trunc_ln415_12_fu_2048_p4 = {{data_12_V_read[9:3]}};

assign trunc_ln415_13_fu_2200_p4 = {{data_13_V_read[9:3]}};

assign trunc_ln415_14_fu_2352_p4 = {{data_14_V_read[9:3]}};

assign trunc_ln415_15_fu_2504_p4 = {{data_15_V_read[9:3]}};

assign trunc_ln415_1_fu_376_p4 = {{data_1_V_read[9:3]}};

assign trunc_ln415_2_fu_528_p4 = {{data_2_V_read[9:3]}};

assign trunc_ln415_3_fu_680_p4 = {{data_3_V_read[9:3]}};

assign trunc_ln415_4_fu_832_p4 = {{data_4_V_read[9:3]}};

assign trunc_ln415_5_fu_984_p4 = {{data_5_V_read[9:3]}};

assign trunc_ln415_6_fu_1136_p4 = {{data_6_V_read[9:3]}};

assign trunc_ln415_7_fu_1288_p4 = {{data_7_V_read[9:3]}};

assign trunc_ln415_8_fu_1440_p4 = {{data_8_V_read[9:3]}};

assign trunc_ln415_9_fu_1592_p4 = {{data_9_V_read[9:3]}};

assign trunc_ln415_s_fu_224_p4 = {{data_0_V_read[9:3]}};

assign trunc_ln708_10_fu_1862_p4 = {{data_11_V_read[10:3]}};

assign trunc_ln708_11_fu_2014_p4 = {{data_12_V_read[10:3]}};

assign trunc_ln708_12_fu_2166_p4 = {{data_13_V_read[10:3]}};

assign trunc_ln708_13_fu_2318_p4 = {{data_14_V_read[10:3]}};

assign trunc_ln708_14_fu_2470_p4 = {{data_15_V_read[10:3]}};

assign trunc_ln708_1_fu_494_p4 = {{data_2_V_read[10:3]}};

assign trunc_ln708_2_fu_646_p4 = {{data_3_V_read[10:3]}};

assign trunc_ln708_3_fu_798_p4 = {{data_4_V_read[10:3]}};

assign trunc_ln708_4_fu_950_p4 = {{data_5_V_read[10:3]}};

assign trunc_ln708_5_fu_1102_p4 = {{data_6_V_read[10:3]}};

assign trunc_ln708_6_fu_1254_p4 = {{data_7_V_read[10:3]}};

assign trunc_ln708_7_fu_1406_p4 = {{data_8_V_read[10:3]}};

assign trunc_ln708_8_fu_1558_p4 = {{data_9_V_read[10:3]}};

assign trunc_ln708_9_fu_1710_p4 = {{data_10_V_read[10:3]}};

assign trunc_ln708_s_fu_342_p4 = {{data_1_V_read[10:3]}};

assign trunc_ln_fu_190_p4 = {{data_0_V_read[10:3]}};

assign xor_ln416_10_fu_1774_p2 = (tmp_138_fu_1766_p3 ^ 1'd1);

assign xor_ln416_11_fu_1926_p2 = (tmp_142_fu_1918_p3 ^ 1'd1);

assign xor_ln416_12_fu_2078_p2 = (tmp_146_fu_2070_p3 ^ 1'd1);

assign xor_ln416_13_fu_2230_p2 = (tmp_150_fu_2222_p3 ^ 1'd1);

assign xor_ln416_14_fu_2382_p2 = (tmp_154_fu_2374_p3 ^ 1'd1);

assign xor_ln416_15_fu_2534_p2 = (tmp_158_fu_2526_p3 ^ 1'd1);

assign xor_ln416_1_fu_406_p2 = (tmp_102_fu_398_p3 ^ 1'd1);

assign xor_ln416_2_fu_558_p2 = (tmp_106_fu_550_p3 ^ 1'd1);

assign xor_ln416_3_fu_710_p2 = (tmp_110_fu_702_p3 ^ 1'd1);

assign xor_ln416_4_fu_862_p2 = (tmp_114_fu_854_p3 ^ 1'd1);

assign xor_ln416_5_fu_1014_p2 = (tmp_118_fu_1006_p3 ^ 1'd1);

assign xor_ln416_6_fu_1166_p2 = (tmp_122_fu_1158_p3 ^ 1'd1);

assign xor_ln416_7_fu_1318_p2 = (tmp_126_fu_1310_p3 ^ 1'd1);

assign xor_ln416_8_fu_1470_p2 = (tmp_130_fu_1462_p3 ^ 1'd1);

assign xor_ln416_9_fu_1622_p2 = (tmp_134_fu_1614_p3 ^ 1'd1);

assign xor_ln416_fu_254_p2 = (tmp_98_fu_246_p3 ^ 1'd1);

assign xor_ln785_10_fu_1824_p2 = (select_ln777_10_fu_1816_p3 ^ 1'd1);

assign xor_ln785_11_fu_1976_p2 = (select_ln777_11_fu_1968_p3 ^ 1'd1);

assign xor_ln785_12_fu_2128_p2 = (select_ln777_12_fu_2120_p3 ^ 1'd1);

assign xor_ln785_13_fu_2280_p2 = (select_ln777_13_fu_2272_p3 ^ 1'd1);

assign xor_ln785_14_fu_2432_p2 = (select_ln777_14_fu_2424_p3 ^ 1'd1);

assign xor_ln785_15_fu_2584_p2 = (select_ln777_15_fu_2576_p3 ^ 1'd1);

assign xor_ln785_1_fu_456_p2 = (select_ln777_1_fu_448_p3 ^ 1'd1);

assign xor_ln785_2_fu_608_p2 = (select_ln777_2_fu_600_p3 ^ 1'd1);

assign xor_ln785_3_fu_760_p2 = (select_ln777_3_fu_752_p3 ^ 1'd1);

assign xor_ln785_4_fu_912_p2 = (select_ln777_4_fu_904_p3 ^ 1'd1);

assign xor_ln785_5_fu_1064_p2 = (select_ln777_5_fu_1056_p3 ^ 1'd1);

assign xor_ln785_6_fu_1216_p2 = (select_ln777_6_fu_1208_p3 ^ 1'd1);

assign xor_ln785_7_fu_1368_p2 = (select_ln777_7_fu_1360_p3 ^ 1'd1);

assign xor_ln785_8_fu_1520_p2 = (select_ln777_8_fu_1512_p3 ^ 1'd1);

assign xor_ln785_9_fu_1672_p2 = (select_ln777_9_fu_1664_p3 ^ 1'd1);

assign xor_ln785_fu_304_p2 = (select_ln777_fu_296_p3 ^ 1'd1);

assign zext_ln1494_10_fu_1852_p1 = select_ln1494_10_fu_1844_p3;

assign zext_ln1494_11_fu_2004_p1 = select_ln1494_11_fu_1996_p3;

assign zext_ln1494_12_fu_2156_p1 = select_ln1494_12_fu_2148_p3;

assign zext_ln1494_13_fu_2308_p1 = select_ln1494_13_fu_2300_p3;

assign zext_ln1494_14_fu_2460_p1 = select_ln1494_14_fu_2452_p3;

assign zext_ln1494_15_fu_2612_p1 = select_ln1494_15_fu_2604_p3;

assign zext_ln1494_1_fu_484_p1 = select_ln1494_1_fu_476_p3;

assign zext_ln1494_2_fu_636_p1 = select_ln1494_2_fu_628_p3;

assign zext_ln1494_3_fu_788_p1 = select_ln1494_3_fu_780_p3;

assign zext_ln1494_4_fu_940_p1 = select_ln1494_4_fu_932_p3;

assign zext_ln1494_5_fu_1092_p1 = select_ln1494_5_fu_1084_p3;

assign zext_ln1494_6_fu_1244_p1 = select_ln1494_6_fu_1236_p3;

assign zext_ln1494_7_fu_1396_p1 = select_ln1494_7_fu_1388_p3;

assign zext_ln1494_8_fu_1548_p1 = select_ln1494_8_fu_1540_p3;

assign zext_ln1494_9_fu_1700_p1 = select_ln1494_9_fu_1692_p3;

assign zext_ln1494_fu_332_p1 = select_ln1494_fu_324_p3;

assign zext_ln415_32_fu_220_p1 = tmp_97_fu_208_p3;

assign zext_ln415_33_fu_368_p1 = tmp_101_fu_360_p3;

assign zext_ln415_34_fu_372_p1 = tmp_101_fu_360_p3;

assign zext_ln415_35_fu_520_p1 = tmp_105_fu_512_p3;

assign zext_ln415_36_fu_524_p1 = tmp_105_fu_512_p3;

assign zext_ln415_37_fu_672_p1 = tmp_109_fu_664_p3;

assign zext_ln415_38_fu_676_p1 = tmp_109_fu_664_p3;

assign zext_ln415_39_fu_824_p1 = tmp_113_fu_816_p3;

assign zext_ln415_40_fu_828_p1 = tmp_113_fu_816_p3;

assign zext_ln415_41_fu_976_p1 = tmp_117_fu_968_p3;

assign zext_ln415_42_fu_980_p1 = tmp_117_fu_968_p3;

assign zext_ln415_43_fu_1128_p1 = tmp_121_fu_1120_p3;

assign zext_ln415_44_fu_1132_p1 = tmp_121_fu_1120_p3;

assign zext_ln415_45_fu_1280_p1 = tmp_125_fu_1272_p3;

assign zext_ln415_46_fu_1284_p1 = tmp_125_fu_1272_p3;

assign zext_ln415_47_fu_1432_p1 = tmp_129_fu_1424_p3;

assign zext_ln415_48_fu_1436_p1 = tmp_129_fu_1424_p3;

assign zext_ln415_49_fu_1584_p1 = tmp_133_fu_1576_p3;

assign zext_ln415_50_fu_1588_p1 = tmp_133_fu_1576_p3;

assign zext_ln415_51_fu_1736_p1 = tmp_137_fu_1728_p3;

assign zext_ln415_52_fu_1740_p1 = tmp_137_fu_1728_p3;

assign zext_ln415_53_fu_1888_p1 = tmp_141_fu_1880_p3;

assign zext_ln415_54_fu_1892_p1 = tmp_141_fu_1880_p3;

assign zext_ln415_55_fu_2040_p1 = tmp_145_fu_2032_p3;

assign zext_ln415_56_fu_2044_p1 = tmp_145_fu_2032_p3;

assign zext_ln415_57_fu_2192_p1 = tmp_149_fu_2184_p3;

assign zext_ln415_58_fu_2196_p1 = tmp_149_fu_2184_p3;

assign zext_ln415_59_fu_2344_p1 = tmp_153_fu_2336_p3;

assign zext_ln415_60_fu_2348_p1 = tmp_153_fu_2336_p3;

assign zext_ln415_61_fu_2496_p1 = tmp_157_fu_2488_p3;

assign zext_ln415_62_fu_2500_p1 = tmp_157_fu_2488_p3;

assign zext_ln415_fu_216_p1 = tmp_97_fu_208_p3;

endmodule //relu
