// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19
);


output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_17_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_19_V_read;
output  [6:0] ap_return_0;
output  [6:0] ap_return_1;
output  [6:0] ap_return_2;
output  [6:0] ap_return_3;
output  [6:0] ap_return_4;
output  [6:0] ap_return_5;
output  [6:0] ap_return_6;
output  [6:0] ap_return_7;
output  [6:0] ap_return_8;
output  [6:0] ap_return_9;
output  [6:0] ap_return_10;
output  [6:0] ap_return_11;
output  [6:0] ap_return_12;
output  [6:0] ap_return_13;
output  [6:0] ap_return_14;
output  [6:0] ap_return_15;
output  [6:0] ap_return_16;
output  [6:0] ap_return_17;
output  [6:0] ap_return_18;
output  [6:0] ap_return_19;

wire   [0:0] tmp_97_fu_240_p3;
wire   [6:0] zext_ln415_fu_248_p1;
wire   [6:0] trunc_ln_fu_222_p4;
wire   [5:0] trunc_ln415_s_fu_256_p4;
wire   [5:0] zext_ln415_32_fu_252_p1;
wire   [6:0] add_ln415_fu_266_p2;
wire   [0:0] tmp_98_fu_278_p3;
wire   [0:0] tmp_96_fu_232_p3;
wire   [0:0] xor_ln416_fu_286_p2;
wire   [3:0] p_Result_s_fu_306_p4;
wire   [0:0] and_ln416_fu_292_p2;
wire   [0:0] icmp_ln879_fu_316_p2;
wire   [0:0] icmp_ln768_fu_322_p2;
wire   [0:0] select_ln777_fu_328_p3;
wire   [0:0] tmp_99_fu_298_p3;
wire   [0:0] xor_ln785_fu_336_p2;
wire   [0:0] or_ln340_fu_342_p2;
wire   [5:0] add_ln416_fu_272_p2;
wire   [0:0] icmp_ln1494_fu_216_p2;
wire   [5:0] select_ln340_fu_348_p3;
wire   [5:0] select_ln1494_fu_356_p3;
wire   [0:0] tmp_101_fu_392_p3;
wire   [6:0] zext_ln415_33_fu_400_p1;
wire   [6:0] trunc_ln708_s_fu_374_p4;
wire   [5:0] trunc_ln415_1_fu_408_p4;
wire   [5:0] zext_ln415_34_fu_404_p1;
wire   [6:0] add_ln415_16_fu_418_p2;
wire   [0:0] tmp_102_fu_430_p3;
wire   [0:0] tmp_100_fu_384_p3;
wire   [0:0] xor_ln416_1_fu_438_p2;
wire   [3:0] p_Result_12_1_fu_458_p4;
wire   [0:0] and_ln416_1_fu_444_p2;
wire   [0:0] icmp_ln879_1_fu_468_p2;
wire   [0:0] icmp_ln768_1_fu_474_p2;
wire   [0:0] select_ln777_1_fu_480_p3;
wire   [0:0] tmp_103_fu_450_p3;
wire   [0:0] xor_ln785_1_fu_488_p2;
wire   [0:0] or_ln340_1_fu_494_p2;
wire   [5:0] add_ln416_1_fu_424_p2;
wire   [0:0] icmp_ln1494_1_fu_368_p2;
wire   [5:0] select_ln340_1_fu_500_p3;
wire   [5:0] select_ln1494_1_fu_508_p3;
wire   [0:0] tmp_105_fu_544_p3;
wire   [6:0] zext_ln415_35_fu_552_p1;
wire   [6:0] trunc_ln708_1_fu_526_p4;
wire   [5:0] trunc_ln415_2_fu_560_p4;
wire   [5:0] zext_ln415_36_fu_556_p1;
wire   [6:0] add_ln415_17_fu_570_p2;
wire   [0:0] tmp_106_fu_582_p3;
wire   [0:0] tmp_104_fu_536_p3;
wire   [0:0] xor_ln416_2_fu_590_p2;
wire   [3:0] p_Result_12_2_fu_610_p4;
wire   [0:0] and_ln416_2_fu_596_p2;
wire   [0:0] icmp_ln879_2_fu_620_p2;
wire   [0:0] icmp_ln768_2_fu_626_p2;
wire   [0:0] select_ln777_2_fu_632_p3;
wire   [0:0] tmp_107_fu_602_p3;
wire   [0:0] xor_ln785_2_fu_640_p2;
wire   [0:0] or_ln340_2_fu_646_p2;
wire   [5:0] add_ln416_2_fu_576_p2;
wire   [0:0] icmp_ln1494_2_fu_520_p2;
wire   [5:0] select_ln340_2_fu_652_p3;
wire   [5:0] select_ln1494_2_fu_660_p3;
wire   [0:0] tmp_109_fu_696_p3;
wire   [6:0] zext_ln415_37_fu_704_p1;
wire   [6:0] trunc_ln708_2_fu_678_p4;
wire   [5:0] trunc_ln415_3_fu_712_p4;
wire   [5:0] zext_ln415_38_fu_708_p1;
wire   [6:0] add_ln415_18_fu_722_p2;
wire   [0:0] tmp_110_fu_734_p3;
wire   [0:0] tmp_108_fu_688_p3;
wire   [0:0] xor_ln416_3_fu_742_p2;
wire   [3:0] p_Result_12_3_fu_762_p4;
wire   [0:0] and_ln416_3_fu_748_p2;
wire   [0:0] icmp_ln879_3_fu_772_p2;
wire   [0:0] icmp_ln768_3_fu_778_p2;
wire   [0:0] select_ln777_3_fu_784_p3;
wire   [0:0] tmp_111_fu_754_p3;
wire   [0:0] xor_ln785_3_fu_792_p2;
wire   [0:0] or_ln340_3_fu_798_p2;
wire   [5:0] add_ln416_3_fu_728_p2;
wire   [0:0] icmp_ln1494_3_fu_672_p2;
wire   [5:0] select_ln340_3_fu_804_p3;
wire   [5:0] select_ln1494_3_fu_812_p3;
wire   [0:0] tmp_113_fu_848_p3;
wire   [6:0] zext_ln415_39_fu_856_p1;
wire   [6:0] trunc_ln708_3_fu_830_p4;
wire   [5:0] trunc_ln415_4_fu_864_p4;
wire   [5:0] zext_ln415_40_fu_860_p1;
wire   [6:0] add_ln415_19_fu_874_p2;
wire   [0:0] tmp_114_fu_886_p3;
wire   [0:0] tmp_112_fu_840_p3;
wire   [0:0] xor_ln416_4_fu_894_p2;
wire   [3:0] p_Result_12_4_fu_914_p4;
wire   [0:0] and_ln416_4_fu_900_p2;
wire   [0:0] icmp_ln879_4_fu_924_p2;
wire   [0:0] icmp_ln768_4_fu_930_p2;
wire   [0:0] select_ln777_4_fu_936_p3;
wire   [0:0] tmp_115_fu_906_p3;
wire   [0:0] xor_ln785_4_fu_944_p2;
wire   [0:0] or_ln340_4_fu_950_p2;
wire   [5:0] add_ln416_4_fu_880_p2;
wire   [0:0] icmp_ln1494_4_fu_824_p2;
wire   [5:0] select_ln340_4_fu_956_p3;
wire   [5:0] select_ln1494_4_fu_964_p3;
wire   [0:0] tmp_117_fu_1000_p3;
wire   [6:0] zext_ln415_41_fu_1008_p1;
wire   [6:0] trunc_ln708_4_fu_982_p4;
wire   [5:0] trunc_ln415_5_fu_1016_p4;
wire   [5:0] zext_ln415_42_fu_1012_p1;
wire   [6:0] add_ln415_20_fu_1026_p2;
wire   [0:0] tmp_118_fu_1038_p3;
wire   [0:0] tmp_116_fu_992_p3;
wire   [0:0] xor_ln416_5_fu_1046_p2;
wire   [3:0] p_Result_12_5_fu_1066_p4;
wire   [0:0] and_ln416_5_fu_1052_p2;
wire   [0:0] icmp_ln879_5_fu_1076_p2;
wire   [0:0] icmp_ln768_5_fu_1082_p2;
wire   [0:0] select_ln777_5_fu_1088_p3;
wire   [0:0] tmp_119_fu_1058_p3;
wire   [0:0] xor_ln785_5_fu_1096_p2;
wire   [0:0] or_ln340_5_fu_1102_p2;
wire   [5:0] add_ln416_5_fu_1032_p2;
wire   [0:0] icmp_ln1494_5_fu_976_p2;
wire   [5:0] select_ln340_5_fu_1108_p3;
wire   [5:0] select_ln1494_5_fu_1116_p3;
wire   [0:0] tmp_121_fu_1152_p3;
wire   [6:0] zext_ln415_43_fu_1160_p1;
wire   [6:0] trunc_ln708_5_fu_1134_p4;
wire   [5:0] trunc_ln415_6_fu_1168_p4;
wire   [5:0] zext_ln415_44_fu_1164_p1;
wire   [6:0] add_ln415_21_fu_1178_p2;
wire   [0:0] tmp_122_fu_1190_p3;
wire   [0:0] tmp_120_fu_1144_p3;
wire   [0:0] xor_ln416_6_fu_1198_p2;
wire   [3:0] p_Result_12_6_fu_1218_p4;
wire   [0:0] and_ln416_6_fu_1204_p2;
wire   [0:0] icmp_ln879_6_fu_1228_p2;
wire   [0:0] icmp_ln768_6_fu_1234_p2;
wire   [0:0] select_ln777_6_fu_1240_p3;
wire   [0:0] tmp_123_fu_1210_p3;
wire   [0:0] xor_ln785_6_fu_1248_p2;
wire   [0:0] or_ln340_6_fu_1254_p2;
wire   [5:0] add_ln416_6_fu_1184_p2;
wire   [0:0] icmp_ln1494_6_fu_1128_p2;
wire   [5:0] select_ln340_6_fu_1260_p3;
wire   [5:0] select_ln1494_6_fu_1268_p3;
wire   [0:0] tmp_125_fu_1304_p3;
wire   [6:0] zext_ln415_45_fu_1312_p1;
wire   [6:0] trunc_ln708_6_fu_1286_p4;
wire   [5:0] trunc_ln415_7_fu_1320_p4;
wire   [5:0] zext_ln415_46_fu_1316_p1;
wire   [6:0] add_ln415_22_fu_1330_p2;
wire   [0:0] tmp_126_fu_1342_p3;
wire   [0:0] tmp_124_fu_1296_p3;
wire   [0:0] xor_ln416_7_fu_1350_p2;
wire   [3:0] p_Result_12_7_fu_1370_p4;
wire   [0:0] and_ln416_7_fu_1356_p2;
wire   [0:0] icmp_ln879_7_fu_1380_p2;
wire   [0:0] icmp_ln768_7_fu_1386_p2;
wire   [0:0] select_ln777_7_fu_1392_p3;
wire   [0:0] tmp_127_fu_1362_p3;
wire   [0:0] xor_ln785_7_fu_1400_p2;
wire   [0:0] or_ln340_7_fu_1406_p2;
wire   [5:0] add_ln416_7_fu_1336_p2;
wire   [0:0] icmp_ln1494_7_fu_1280_p2;
wire   [5:0] select_ln340_7_fu_1412_p3;
wire   [5:0] select_ln1494_7_fu_1420_p3;
wire   [0:0] tmp_129_fu_1456_p3;
wire   [6:0] zext_ln415_47_fu_1464_p1;
wire   [6:0] trunc_ln708_7_fu_1438_p4;
wire   [5:0] trunc_ln415_8_fu_1472_p4;
wire   [5:0] zext_ln415_48_fu_1468_p1;
wire   [6:0] add_ln415_23_fu_1482_p2;
wire   [0:0] tmp_130_fu_1494_p3;
wire   [0:0] tmp_128_fu_1448_p3;
wire   [0:0] xor_ln416_8_fu_1502_p2;
wire   [3:0] p_Result_12_8_fu_1522_p4;
wire   [0:0] and_ln416_8_fu_1508_p2;
wire   [0:0] icmp_ln879_8_fu_1532_p2;
wire   [0:0] icmp_ln768_8_fu_1538_p2;
wire   [0:0] select_ln777_8_fu_1544_p3;
wire   [0:0] tmp_131_fu_1514_p3;
wire   [0:0] xor_ln785_8_fu_1552_p2;
wire   [0:0] or_ln340_8_fu_1558_p2;
wire   [5:0] add_ln416_8_fu_1488_p2;
wire   [0:0] icmp_ln1494_8_fu_1432_p2;
wire   [5:0] select_ln340_8_fu_1564_p3;
wire   [5:0] select_ln1494_8_fu_1572_p3;
wire   [0:0] tmp_133_fu_1608_p3;
wire   [6:0] zext_ln415_49_fu_1616_p1;
wire   [6:0] trunc_ln708_8_fu_1590_p4;
wire   [5:0] trunc_ln415_9_fu_1624_p4;
wire   [5:0] zext_ln415_50_fu_1620_p1;
wire   [6:0] add_ln415_24_fu_1634_p2;
wire   [0:0] tmp_134_fu_1646_p3;
wire   [0:0] tmp_132_fu_1600_p3;
wire   [0:0] xor_ln416_9_fu_1654_p2;
wire   [3:0] p_Result_12_9_fu_1674_p4;
wire   [0:0] and_ln416_9_fu_1660_p2;
wire   [0:0] icmp_ln879_9_fu_1684_p2;
wire   [0:0] icmp_ln768_9_fu_1690_p2;
wire   [0:0] select_ln777_9_fu_1696_p3;
wire   [0:0] tmp_135_fu_1666_p3;
wire   [0:0] xor_ln785_9_fu_1704_p2;
wire   [0:0] or_ln340_9_fu_1710_p2;
wire   [5:0] add_ln416_9_fu_1640_p2;
wire   [0:0] icmp_ln1494_9_fu_1584_p2;
wire   [5:0] select_ln340_9_fu_1716_p3;
wire   [5:0] select_ln1494_9_fu_1724_p3;
wire   [0:0] tmp_137_fu_1760_p3;
wire   [6:0] zext_ln415_51_fu_1768_p1;
wire   [6:0] trunc_ln708_9_fu_1742_p4;
wire   [5:0] trunc_ln415_10_fu_1776_p4;
wire   [5:0] zext_ln415_52_fu_1772_p1;
wire   [6:0] add_ln415_25_fu_1786_p2;
wire   [0:0] tmp_138_fu_1798_p3;
wire   [0:0] tmp_136_fu_1752_p3;
wire   [0:0] xor_ln416_10_fu_1806_p2;
wire   [3:0] p_Result_12_s_fu_1826_p4;
wire   [0:0] and_ln416_10_fu_1812_p2;
wire   [0:0] icmp_ln879_10_fu_1836_p2;
wire   [0:0] icmp_ln768_10_fu_1842_p2;
wire   [0:0] select_ln777_10_fu_1848_p3;
wire   [0:0] tmp_139_fu_1818_p3;
wire   [0:0] xor_ln785_10_fu_1856_p2;
wire   [0:0] or_ln340_10_fu_1862_p2;
wire   [5:0] add_ln416_10_fu_1792_p2;
wire   [0:0] icmp_ln1494_10_fu_1736_p2;
wire   [5:0] select_ln340_10_fu_1868_p3;
wire   [5:0] select_ln1494_10_fu_1876_p3;
wire   [0:0] tmp_141_fu_1912_p3;
wire   [6:0] zext_ln415_53_fu_1920_p1;
wire   [6:0] trunc_ln708_10_fu_1894_p4;
wire   [5:0] trunc_ln415_11_fu_1928_p4;
wire   [5:0] zext_ln415_54_fu_1924_p1;
wire   [6:0] add_ln415_26_fu_1938_p2;
wire   [0:0] tmp_142_fu_1950_p3;
wire   [0:0] tmp_140_fu_1904_p3;
wire   [0:0] xor_ln416_11_fu_1958_p2;
wire   [3:0] p_Result_12_10_fu_1978_p4;
wire   [0:0] and_ln416_11_fu_1964_p2;
wire   [0:0] icmp_ln879_11_fu_1988_p2;
wire   [0:0] icmp_ln768_11_fu_1994_p2;
wire   [0:0] select_ln777_11_fu_2000_p3;
wire   [0:0] tmp_143_fu_1970_p3;
wire   [0:0] xor_ln785_11_fu_2008_p2;
wire   [0:0] or_ln340_11_fu_2014_p2;
wire   [5:0] add_ln416_11_fu_1944_p2;
wire   [0:0] icmp_ln1494_11_fu_1888_p2;
wire   [5:0] select_ln340_11_fu_2020_p3;
wire   [5:0] select_ln1494_11_fu_2028_p3;
wire   [0:0] tmp_145_fu_2064_p3;
wire   [6:0] zext_ln415_55_fu_2072_p1;
wire   [6:0] trunc_ln708_11_fu_2046_p4;
wire   [5:0] trunc_ln415_12_fu_2080_p4;
wire   [5:0] zext_ln415_56_fu_2076_p1;
wire   [6:0] add_ln415_27_fu_2090_p2;
wire   [0:0] tmp_146_fu_2102_p3;
wire   [0:0] tmp_144_fu_2056_p3;
wire   [0:0] xor_ln416_12_fu_2110_p2;
wire   [3:0] p_Result_12_11_fu_2130_p4;
wire   [0:0] and_ln416_12_fu_2116_p2;
wire   [0:0] icmp_ln879_12_fu_2140_p2;
wire   [0:0] icmp_ln768_12_fu_2146_p2;
wire   [0:0] select_ln777_12_fu_2152_p3;
wire   [0:0] tmp_147_fu_2122_p3;
wire   [0:0] xor_ln785_12_fu_2160_p2;
wire   [0:0] or_ln340_12_fu_2166_p2;
wire   [5:0] add_ln416_12_fu_2096_p2;
wire   [0:0] icmp_ln1494_12_fu_2040_p2;
wire   [5:0] select_ln340_12_fu_2172_p3;
wire   [5:0] select_ln1494_12_fu_2180_p3;
wire   [0:0] tmp_149_fu_2216_p3;
wire   [6:0] zext_ln415_57_fu_2224_p1;
wire   [6:0] trunc_ln708_12_fu_2198_p4;
wire   [5:0] trunc_ln415_13_fu_2232_p4;
wire   [5:0] zext_ln415_58_fu_2228_p1;
wire   [6:0] add_ln415_28_fu_2242_p2;
wire   [0:0] tmp_150_fu_2254_p3;
wire   [0:0] tmp_148_fu_2208_p3;
wire   [0:0] xor_ln416_13_fu_2262_p2;
wire   [3:0] p_Result_12_12_fu_2282_p4;
wire   [0:0] and_ln416_13_fu_2268_p2;
wire   [0:0] icmp_ln879_13_fu_2292_p2;
wire   [0:0] icmp_ln768_13_fu_2298_p2;
wire   [0:0] select_ln777_13_fu_2304_p3;
wire   [0:0] tmp_151_fu_2274_p3;
wire   [0:0] xor_ln785_13_fu_2312_p2;
wire   [0:0] or_ln340_13_fu_2318_p2;
wire   [5:0] add_ln416_13_fu_2248_p2;
wire   [0:0] icmp_ln1494_13_fu_2192_p2;
wire   [5:0] select_ln340_13_fu_2324_p3;
wire   [5:0] select_ln1494_13_fu_2332_p3;
wire   [0:0] tmp_153_fu_2368_p3;
wire   [6:0] zext_ln415_59_fu_2376_p1;
wire   [6:0] trunc_ln708_13_fu_2350_p4;
wire   [5:0] trunc_ln415_14_fu_2384_p4;
wire   [5:0] zext_ln415_60_fu_2380_p1;
wire   [6:0] add_ln415_29_fu_2394_p2;
wire   [0:0] tmp_154_fu_2406_p3;
wire   [0:0] tmp_152_fu_2360_p3;
wire   [0:0] xor_ln416_14_fu_2414_p2;
wire   [3:0] p_Result_12_13_fu_2434_p4;
wire   [0:0] and_ln416_14_fu_2420_p2;
wire   [0:0] icmp_ln879_14_fu_2444_p2;
wire   [0:0] icmp_ln768_14_fu_2450_p2;
wire   [0:0] select_ln777_14_fu_2456_p3;
wire   [0:0] tmp_155_fu_2426_p3;
wire   [0:0] xor_ln785_14_fu_2464_p2;
wire   [0:0] or_ln340_14_fu_2470_p2;
wire   [5:0] add_ln416_14_fu_2400_p2;
wire   [0:0] icmp_ln1494_14_fu_2344_p2;
wire   [5:0] select_ln340_14_fu_2476_p3;
wire   [5:0] select_ln1494_14_fu_2484_p3;
wire   [0:0] tmp_157_fu_2520_p3;
wire   [6:0] zext_ln415_61_fu_2528_p1;
wire   [6:0] trunc_ln708_14_fu_2502_p4;
wire   [5:0] trunc_ln415_15_fu_2536_p4;
wire   [5:0] zext_ln415_62_fu_2532_p1;
wire   [6:0] add_ln415_30_fu_2546_p2;
wire   [0:0] tmp_158_fu_2558_p3;
wire   [0:0] tmp_156_fu_2512_p3;
wire   [0:0] xor_ln416_15_fu_2566_p2;
wire   [3:0] p_Result_12_14_fu_2586_p4;
wire   [0:0] and_ln416_15_fu_2572_p2;
wire   [0:0] icmp_ln879_15_fu_2596_p2;
wire   [0:0] icmp_ln768_15_fu_2602_p2;
wire   [0:0] select_ln777_15_fu_2608_p3;
wire   [0:0] tmp_159_fu_2578_p3;
wire   [0:0] xor_ln785_15_fu_2616_p2;
wire   [0:0] or_ln340_15_fu_2622_p2;
wire   [5:0] add_ln416_15_fu_2552_p2;
wire   [0:0] icmp_ln1494_15_fu_2496_p2;
wire   [5:0] select_ln340_15_fu_2628_p3;
wire   [5:0] select_ln1494_15_fu_2636_p3;
wire   [0:0] tmp_161_fu_2672_p3;
wire   [6:0] zext_ln415_63_fu_2680_p1;
wire   [6:0] trunc_ln708_15_fu_2654_p4;
wire   [5:0] trunc_ln415_16_fu_2688_p4;
wire   [5:0] zext_ln415_64_fu_2684_p1;
wire   [6:0] add_ln415_31_fu_2698_p2;
wire   [0:0] tmp_162_fu_2710_p3;
wire   [0:0] tmp_160_fu_2664_p3;
wire   [0:0] xor_ln416_16_fu_2718_p2;
wire   [3:0] p_Result_12_15_fu_2738_p4;
wire   [0:0] and_ln416_16_fu_2724_p2;
wire   [0:0] icmp_ln879_16_fu_2748_p2;
wire   [0:0] icmp_ln768_16_fu_2754_p2;
wire   [0:0] select_ln777_16_fu_2760_p3;
wire   [0:0] tmp_163_fu_2730_p3;
wire   [0:0] xor_ln785_16_fu_2768_p2;
wire   [0:0] or_ln340_16_fu_2774_p2;
wire   [5:0] add_ln416_16_fu_2704_p2;
wire   [0:0] icmp_ln1494_16_fu_2648_p2;
wire   [5:0] select_ln340_16_fu_2780_p3;
wire   [5:0] select_ln1494_16_fu_2788_p3;
wire   [0:0] tmp_165_fu_2824_p3;
wire   [6:0] zext_ln415_65_fu_2832_p1;
wire   [6:0] trunc_ln708_16_fu_2806_p4;
wire   [5:0] trunc_ln415_17_fu_2840_p4;
wire   [5:0] zext_ln415_66_fu_2836_p1;
wire   [6:0] add_ln415_32_fu_2850_p2;
wire   [0:0] tmp_166_fu_2862_p3;
wire   [0:0] tmp_164_fu_2816_p3;
wire   [0:0] xor_ln416_17_fu_2870_p2;
wire   [3:0] p_Result_12_16_fu_2890_p4;
wire   [0:0] and_ln416_17_fu_2876_p2;
wire   [0:0] icmp_ln879_17_fu_2900_p2;
wire   [0:0] icmp_ln768_17_fu_2906_p2;
wire   [0:0] select_ln777_17_fu_2912_p3;
wire   [0:0] tmp_167_fu_2882_p3;
wire   [0:0] xor_ln785_17_fu_2920_p2;
wire   [0:0] or_ln340_17_fu_2926_p2;
wire   [5:0] add_ln416_17_fu_2856_p2;
wire   [0:0] icmp_ln1494_17_fu_2800_p2;
wire   [5:0] select_ln340_17_fu_2932_p3;
wire   [5:0] select_ln1494_17_fu_2940_p3;
wire   [0:0] tmp_169_fu_2976_p3;
wire   [6:0] zext_ln415_67_fu_2984_p1;
wire   [6:0] trunc_ln708_17_fu_2958_p4;
wire   [5:0] trunc_ln415_18_fu_2992_p4;
wire   [5:0] zext_ln415_68_fu_2988_p1;
wire   [6:0] add_ln415_33_fu_3002_p2;
wire   [0:0] tmp_170_fu_3014_p3;
wire   [0:0] tmp_168_fu_2968_p3;
wire   [0:0] xor_ln416_18_fu_3022_p2;
wire   [3:0] p_Result_12_17_fu_3042_p4;
wire   [0:0] and_ln416_18_fu_3028_p2;
wire   [0:0] icmp_ln879_18_fu_3052_p2;
wire   [0:0] icmp_ln768_18_fu_3058_p2;
wire   [0:0] select_ln777_18_fu_3064_p3;
wire   [0:0] tmp_171_fu_3034_p3;
wire   [0:0] xor_ln785_18_fu_3072_p2;
wire   [0:0] or_ln340_18_fu_3078_p2;
wire   [5:0] add_ln416_18_fu_3008_p2;
wire   [0:0] icmp_ln1494_18_fu_2952_p2;
wire   [5:0] select_ln340_18_fu_3084_p3;
wire   [5:0] select_ln1494_18_fu_3092_p3;
wire   [0:0] tmp_173_fu_3128_p3;
wire   [6:0] zext_ln415_69_fu_3136_p1;
wire   [6:0] trunc_ln708_18_fu_3110_p4;
wire   [5:0] trunc_ln415_19_fu_3144_p4;
wire   [5:0] zext_ln415_70_fu_3140_p1;
wire   [6:0] add_ln415_34_fu_3154_p2;
wire   [0:0] tmp_174_fu_3166_p3;
wire   [0:0] tmp_172_fu_3120_p3;
wire   [0:0] xor_ln416_19_fu_3174_p2;
wire   [3:0] p_Result_12_18_fu_3194_p4;
wire   [0:0] and_ln416_19_fu_3180_p2;
wire   [0:0] icmp_ln879_19_fu_3204_p2;
wire   [0:0] icmp_ln768_19_fu_3210_p2;
wire   [0:0] select_ln777_19_fu_3216_p3;
wire   [0:0] tmp_175_fu_3186_p3;
wire   [0:0] xor_ln785_19_fu_3224_p2;
wire   [0:0] or_ln340_19_fu_3230_p2;
wire   [5:0] add_ln416_19_fu_3160_p2;
wire   [0:0] icmp_ln1494_19_fu_3104_p2;
wire   [5:0] select_ln340_19_fu_3236_p3;
wire   [5:0] select_ln1494_19_fu_3244_p3;
wire   [6:0] zext_ln1494_fu_364_p1;
wire   [6:0] zext_ln1494_1_fu_516_p1;
wire   [6:0] zext_ln1494_2_fu_668_p1;
wire   [6:0] zext_ln1494_3_fu_820_p1;
wire   [6:0] zext_ln1494_4_fu_972_p1;
wire   [6:0] zext_ln1494_5_fu_1124_p1;
wire   [6:0] zext_ln1494_6_fu_1276_p1;
wire   [6:0] zext_ln1494_7_fu_1428_p1;
wire   [6:0] zext_ln1494_8_fu_1580_p1;
wire   [6:0] zext_ln1494_9_fu_1732_p1;
wire   [6:0] zext_ln1494_10_fu_1884_p1;
wire   [6:0] zext_ln1494_11_fu_2036_p1;
wire   [6:0] zext_ln1494_12_fu_2188_p1;
wire   [6:0] zext_ln1494_13_fu_2340_p1;
wire   [6:0] zext_ln1494_14_fu_2492_p1;
wire   [6:0] zext_ln1494_15_fu_2644_p1;
wire   [6:0] zext_ln1494_16_fu_2796_p1;
wire   [6:0] zext_ln1494_17_fu_2948_p1;
wire   [6:0] zext_ln1494_18_fu_3100_p1;
wire   [6:0] zext_ln1494_19_fu_3252_p1;

assign add_ln415_16_fu_418_p2 = (zext_ln415_33_fu_400_p1 + trunc_ln708_s_fu_374_p4);

assign add_ln415_17_fu_570_p2 = (zext_ln415_35_fu_552_p1 + trunc_ln708_1_fu_526_p4);

assign add_ln415_18_fu_722_p2 = (zext_ln415_37_fu_704_p1 + trunc_ln708_2_fu_678_p4);

assign add_ln415_19_fu_874_p2 = (zext_ln415_39_fu_856_p1 + trunc_ln708_3_fu_830_p4);

assign add_ln415_20_fu_1026_p2 = (zext_ln415_41_fu_1008_p1 + trunc_ln708_4_fu_982_p4);

assign add_ln415_21_fu_1178_p2 = (zext_ln415_43_fu_1160_p1 + trunc_ln708_5_fu_1134_p4);

assign add_ln415_22_fu_1330_p2 = (zext_ln415_45_fu_1312_p1 + trunc_ln708_6_fu_1286_p4);

assign add_ln415_23_fu_1482_p2 = (zext_ln415_47_fu_1464_p1 + trunc_ln708_7_fu_1438_p4);

assign add_ln415_24_fu_1634_p2 = (zext_ln415_49_fu_1616_p1 + trunc_ln708_8_fu_1590_p4);

assign add_ln415_25_fu_1786_p2 = (zext_ln415_51_fu_1768_p1 + trunc_ln708_9_fu_1742_p4);

assign add_ln415_26_fu_1938_p2 = (zext_ln415_53_fu_1920_p1 + trunc_ln708_10_fu_1894_p4);

assign add_ln415_27_fu_2090_p2 = (zext_ln415_55_fu_2072_p1 + trunc_ln708_11_fu_2046_p4);

assign add_ln415_28_fu_2242_p2 = (zext_ln415_57_fu_2224_p1 + trunc_ln708_12_fu_2198_p4);

assign add_ln415_29_fu_2394_p2 = (zext_ln415_59_fu_2376_p1 + trunc_ln708_13_fu_2350_p4);

assign add_ln415_30_fu_2546_p2 = (zext_ln415_61_fu_2528_p1 + trunc_ln708_14_fu_2502_p4);

assign add_ln415_31_fu_2698_p2 = (zext_ln415_63_fu_2680_p1 + trunc_ln708_15_fu_2654_p4);

assign add_ln415_32_fu_2850_p2 = (zext_ln415_65_fu_2832_p1 + trunc_ln708_16_fu_2806_p4);

assign add_ln415_33_fu_3002_p2 = (zext_ln415_67_fu_2984_p1 + trunc_ln708_17_fu_2958_p4);

assign add_ln415_34_fu_3154_p2 = (zext_ln415_69_fu_3136_p1 + trunc_ln708_18_fu_3110_p4);

assign add_ln415_fu_266_p2 = (zext_ln415_fu_248_p1 + trunc_ln_fu_222_p4);

assign add_ln416_10_fu_1792_p2 = (trunc_ln415_10_fu_1776_p4 + zext_ln415_52_fu_1772_p1);

assign add_ln416_11_fu_1944_p2 = (trunc_ln415_11_fu_1928_p4 + zext_ln415_54_fu_1924_p1);

assign add_ln416_12_fu_2096_p2 = (trunc_ln415_12_fu_2080_p4 + zext_ln415_56_fu_2076_p1);

assign add_ln416_13_fu_2248_p2 = (trunc_ln415_13_fu_2232_p4 + zext_ln415_58_fu_2228_p1);

assign add_ln416_14_fu_2400_p2 = (trunc_ln415_14_fu_2384_p4 + zext_ln415_60_fu_2380_p1);

assign add_ln416_15_fu_2552_p2 = (trunc_ln415_15_fu_2536_p4 + zext_ln415_62_fu_2532_p1);

assign add_ln416_16_fu_2704_p2 = (trunc_ln415_16_fu_2688_p4 + zext_ln415_64_fu_2684_p1);

assign add_ln416_17_fu_2856_p2 = (trunc_ln415_17_fu_2840_p4 + zext_ln415_66_fu_2836_p1);

assign add_ln416_18_fu_3008_p2 = (trunc_ln415_18_fu_2992_p4 + zext_ln415_68_fu_2988_p1);

assign add_ln416_19_fu_3160_p2 = (trunc_ln415_19_fu_3144_p4 + zext_ln415_70_fu_3140_p1);

assign add_ln416_1_fu_424_p2 = (trunc_ln415_1_fu_408_p4 + zext_ln415_34_fu_404_p1);

assign add_ln416_2_fu_576_p2 = (trunc_ln415_2_fu_560_p4 + zext_ln415_36_fu_556_p1);

assign add_ln416_3_fu_728_p2 = (trunc_ln415_3_fu_712_p4 + zext_ln415_38_fu_708_p1);

assign add_ln416_4_fu_880_p2 = (trunc_ln415_4_fu_864_p4 + zext_ln415_40_fu_860_p1);

assign add_ln416_5_fu_1032_p2 = (trunc_ln415_5_fu_1016_p4 + zext_ln415_42_fu_1012_p1);

assign add_ln416_6_fu_1184_p2 = (trunc_ln415_6_fu_1168_p4 + zext_ln415_44_fu_1164_p1);

assign add_ln416_7_fu_1336_p2 = (trunc_ln415_7_fu_1320_p4 + zext_ln415_46_fu_1316_p1);

assign add_ln416_8_fu_1488_p2 = (trunc_ln415_8_fu_1472_p4 + zext_ln415_48_fu_1468_p1);

assign add_ln416_9_fu_1640_p2 = (trunc_ln415_9_fu_1624_p4 + zext_ln415_50_fu_1620_p1);

assign add_ln416_fu_272_p2 = (trunc_ln415_s_fu_256_p4 + zext_ln415_32_fu_252_p1);

assign and_ln416_10_fu_1812_p2 = (xor_ln416_10_fu_1806_p2 & tmp_136_fu_1752_p3);

assign and_ln416_11_fu_1964_p2 = (xor_ln416_11_fu_1958_p2 & tmp_140_fu_1904_p3);

assign and_ln416_12_fu_2116_p2 = (xor_ln416_12_fu_2110_p2 & tmp_144_fu_2056_p3);

assign and_ln416_13_fu_2268_p2 = (xor_ln416_13_fu_2262_p2 & tmp_148_fu_2208_p3);

assign and_ln416_14_fu_2420_p2 = (xor_ln416_14_fu_2414_p2 & tmp_152_fu_2360_p3);

assign and_ln416_15_fu_2572_p2 = (xor_ln416_15_fu_2566_p2 & tmp_156_fu_2512_p3);

assign and_ln416_16_fu_2724_p2 = (xor_ln416_16_fu_2718_p2 & tmp_160_fu_2664_p3);

assign and_ln416_17_fu_2876_p2 = (xor_ln416_17_fu_2870_p2 & tmp_164_fu_2816_p3);

assign and_ln416_18_fu_3028_p2 = (xor_ln416_18_fu_3022_p2 & tmp_168_fu_2968_p3);

assign and_ln416_19_fu_3180_p2 = (xor_ln416_19_fu_3174_p2 & tmp_172_fu_3120_p3);

assign and_ln416_1_fu_444_p2 = (xor_ln416_1_fu_438_p2 & tmp_100_fu_384_p3);

assign and_ln416_2_fu_596_p2 = (xor_ln416_2_fu_590_p2 & tmp_104_fu_536_p3);

assign and_ln416_3_fu_748_p2 = (xor_ln416_3_fu_742_p2 & tmp_108_fu_688_p3);

assign and_ln416_4_fu_900_p2 = (xor_ln416_4_fu_894_p2 & tmp_112_fu_840_p3);

assign and_ln416_5_fu_1052_p2 = (xor_ln416_5_fu_1046_p2 & tmp_116_fu_992_p3);

assign and_ln416_6_fu_1204_p2 = (xor_ln416_6_fu_1198_p2 & tmp_120_fu_1144_p3);

assign and_ln416_7_fu_1356_p2 = (xor_ln416_7_fu_1350_p2 & tmp_124_fu_1296_p3);

assign and_ln416_8_fu_1508_p2 = (xor_ln416_8_fu_1502_p2 & tmp_128_fu_1448_p3);

assign and_ln416_9_fu_1660_p2 = (xor_ln416_9_fu_1654_p2 & tmp_132_fu_1600_p3);

assign and_ln416_fu_292_p2 = (xor_ln416_fu_286_p2 & tmp_96_fu_232_p3);

assign ap_ready = 1'b1;

assign ap_return_0 = zext_ln1494_fu_364_p1;

assign ap_return_1 = zext_ln1494_1_fu_516_p1;

assign ap_return_10 = zext_ln1494_10_fu_1884_p1;

assign ap_return_11 = zext_ln1494_11_fu_2036_p1;

assign ap_return_12 = zext_ln1494_12_fu_2188_p1;

assign ap_return_13 = zext_ln1494_13_fu_2340_p1;

assign ap_return_14 = zext_ln1494_14_fu_2492_p1;

assign ap_return_15 = zext_ln1494_15_fu_2644_p1;

assign ap_return_16 = zext_ln1494_16_fu_2796_p1;

assign ap_return_17 = zext_ln1494_17_fu_2948_p1;

assign ap_return_18 = zext_ln1494_18_fu_3100_p1;

assign ap_return_19 = zext_ln1494_19_fu_3252_p1;

assign ap_return_2 = zext_ln1494_2_fu_668_p1;

assign ap_return_3 = zext_ln1494_3_fu_820_p1;

assign ap_return_4 = zext_ln1494_4_fu_972_p1;

assign ap_return_5 = zext_ln1494_5_fu_1124_p1;

assign ap_return_6 = zext_ln1494_6_fu_1276_p1;

assign ap_return_7 = zext_ln1494_7_fu_1428_p1;

assign ap_return_8 = zext_ln1494_8_fu_1580_p1;

assign ap_return_9 = zext_ln1494_9_fu_1732_p1;

assign icmp_ln1494_10_fu_1736_p2 = (($signed(data_10_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1888_p2 = (($signed(data_11_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_2040_p2 = (($signed(data_12_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_2192_p2 = (($signed(data_13_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_2344_p2 = (($signed(data_14_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_2496_p2 = (($signed(data_15_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_2648_p2 = (($signed(data_16_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_2800_p2 = (($signed(data_17_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_2952_p2 = (($signed(data_18_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_3104_p2 = (($signed(data_19_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_368_p2 = (($signed(data_1_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_520_p2 = (($signed(data_2_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_672_p2 = (($signed(data_3_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_824_p2 = (($signed(data_4_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_976_p2 = (($signed(data_5_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1128_p2 = (($signed(data_6_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1280_p2 = (($signed(data_7_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1432_p2 = (($signed(data_8_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1584_p2 = (($signed(data_9_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_216_p2 = (($signed(data_0_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln768_10_fu_1842_p2 = ((p_Result_12_s_fu_1826_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_11_fu_1994_p2 = ((p_Result_12_10_fu_1978_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_12_fu_2146_p2 = ((p_Result_12_11_fu_2130_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_13_fu_2298_p2 = ((p_Result_12_12_fu_2282_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_14_fu_2450_p2 = ((p_Result_12_13_fu_2434_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_15_fu_2602_p2 = ((p_Result_12_14_fu_2586_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_16_fu_2754_p2 = ((p_Result_12_15_fu_2738_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_17_fu_2906_p2 = ((p_Result_12_16_fu_2890_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_18_fu_3058_p2 = ((p_Result_12_17_fu_3042_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_19_fu_3210_p2 = ((p_Result_12_18_fu_3194_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_1_fu_474_p2 = ((p_Result_12_1_fu_458_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_2_fu_626_p2 = ((p_Result_12_2_fu_610_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_3_fu_778_p2 = ((p_Result_12_3_fu_762_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_4_fu_930_p2 = ((p_Result_12_4_fu_914_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_5_fu_1082_p2 = ((p_Result_12_5_fu_1066_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_6_fu_1234_p2 = ((p_Result_12_6_fu_1218_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_7_fu_1386_p2 = ((p_Result_12_7_fu_1370_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_8_fu_1538_p2 = ((p_Result_12_8_fu_1522_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_9_fu_1690_p2 = ((p_Result_12_9_fu_1674_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln768_fu_322_p2 = ((p_Result_s_fu_306_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_10_fu_1836_p2 = ((p_Result_12_s_fu_1826_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_11_fu_1988_p2 = ((p_Result_12_10_fu_1978_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_12_fu_2140_p2 = ((p_Result_12_11_fu_2130_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_13_fu_2292_p2 = ((p_Result_12_12_fu_2282_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_14_fu_2444_p2 = ((p_Result_12_13_fu_2434_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_15_fu_2596_p2 = ((p_Result_12_14_fu_2586_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_16_fu_2748_p2 = ((p_Result_12_15_fu_2738_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_17_fu_2900_p2 = ((p_Result_12_16_fu_2890_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_18_fu_3052_p2 = ((p_Result_12_17_fu_3042_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_19_fu_3204_p2 = ((p_Result_12_18_fu_3194_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_468_p2 = ((p_Result_12_1_fu_458_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_620_p2 = ((p_Result_12_2_fu_610_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_3_fu_772_p2 = ((p_Result_12_3_fu_762_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_4_fu_924_p2 = ((p_Result_12_4_fu_914_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_5_fu_1076_p2 = ((p_Result_12_5_fu_1066_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_6_fu_1228_p2 = ((p_Result_12_6_fu_1218_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_7_fu_1380_p2 = ((p_Result_12_7_fu_1370_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_8_fu_1532_p2 = ((p_Result_12_8_fu_1522_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_9_fu_1684_p2 = ((p_Result_12_9_fu_1674_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_316_p2 = ((p_Result_s_fu_306_p4 == 4'd15) ? 1'b1 : 1'b0);

assign or_ln340_10_fu_1862_p2 = (xor_ln785_10_fu_1856_p2 | tmp_139_fu_1818_p3);

assign or_ln340_11_fu_2014_p2 = (xor_ln785_11_fu_2008_p2 | tmp_143_fu_1970_p3);

assign or_ln340_12_fu_2166_p2 = (xor_ln785_12_fu_2160_p2 | tmp_147_fu_2122_p3);

assign or_ln340_13_fu_2318_p2 = (xor_ln785_13_fu_2312_p2 | tmp_151_fu_2274_p3);

assign or_ln340_14_fu_2470_p2 = (xor_ln785_14_fu_2464_p2 | tmp_155_fu_2426_p3);

assign or_ln340_15_fu_2622_p2 = (xor_ln785_15_fu_2616_p2 | tmp_159_fu_2578_p3);

assign or_ln340_16_fu_2774_p2 = (xor_ln785_16_fu_2768_p2 | tmp_163_fu_2730_p3);

assign or_ln340_17_fu_2926_p2 = (xor_ln785_17_fu_2920_p2 | tmp_167_fu_2882_p3);

assign or_ln340_18_fu_3078_p2 = (xor_ln785_18_fu_3072_p2 | tmp_171_fu_3034_p3);

assign or_ln340_19_fu_3230_p2 = (xor_ln785_19_fu_3224_p2 | tmp_175_fu_3186_p3);

assign or_ln340_1_fu_494_p2 = (xor_ln785_1_fu_488_p2 | tmp_103_fu_450_p3);

assign or_ln340_2_fu_646_p2 = (xor_ln785_2_fu_640_p2 | tmp_107_fu_602_p3);

assign or_ln340_3_fu_798_p2 = (xor_ln785_3_fu_792_p2 | tmp_111_fu_754_p3);

assign or_ln340_4_fu_950_p2 = (xor_ln785_4_fu_944_p2 | tmp_115_fu_906_p3);

assign or_ln340_5_fu_1102_p2 = (xor_ln785_5_fu_1096_p2 | tmp_119_fu_1058_p3);

assign or_ln340_6_fu_1254_p2 = (xor_ln785_6_fu_1248_p2 | tmp_123_fu_1210_p3);

assign or_ln340_7_fu_1406_p2 = (xor_ln785_7_fu_1400_p2 | tmp_127_fu_1362_p3);

assign or_ln340_8_fu_1558_p2 = (xor_ln785_8_fu_1552_p2 | tmp_131_fu_1514_p3);

assign or_ln340_9_fu_1710_p2 = (xor_ln785_9_fu_1704_p2 | tmp_135_fu_1666_p3);

assign or_ln340_fu_342_p2 = (xor_ln785_fu_336_p2 | tmp_99_fu_298_p3);

assign p_Result_12_10_fu_1978_p4 = {{data_11_V_read[15:12]}};

assign p_Result_12_11_fu_2130_p4 = {{data_12_V_read[15:12]}};

assign p_Result_12_12_fu_2282_p4 = {{data_13_V_read[15:12]}};

assign p_Result_12_13_fu_2434_p4 = {{data_14_V_read[15:12]}};

assign p_Result_12_14_fu_2586_p4 = {{data_15_V_read[15:12]}};

assign p_Result_12_15_fu_2738_p4 = {{data_16_V_read[15:12]}};

assign p_Result_12_16_fu_2890_p4 = {{data_17_V_read[15:12]}};

assign p_Result_12_17_fu_3042_p4 = {{data_18_V_read[15:12]}};

assign p_Result_12_18_fu_3194_p4 = {{data_19_V_read[15:12]}};

assign p_Result_12_1_fu_458_p4 = {{data_1_V_read[15:12]}};

assign p_Result_12_2_fu_610_p4 = {{data_2_V_read[15:12]}};

assign p_Result_12_3_fu_762_p4 = {{data_3_V_read[15:12]}};

assign p_Result_12_4_fu_914_p4 = {{data_4_V_read[15:12]}};

assign p_Result_12_5_fu_1066_p4 = {{data_5_V_read[15:12]}};

assign p_Result_12_6_fu_1218_p4 = {{data_6_V_read[15:12]}};

assign p_Result_12_7_fu_1370_p4 = {{data_7_V_read[15:12]}};

assign p_Result_12_8_fu_1522_p4 = {{data_8_V_read[15:12]}};

assign p_Result_12_9_fu_1674_p4 = {{data_9_V_read[15:12]}};

assign p_Result_12_s_fu_1826_p4 = {{data_10_V_read[15:12]}};

assign p_Result_s_fu_306_p4 = {{data_0_V_read[15:12]}};

assign select_ln1494_10_fu_1876_p3 = ((icmp_ln1494_10_fu_1736_p2[0:0] === 1'b1) ? select_ln340_10_fu_1868_p3 : 6'd0);

assign select_ln1494_11_fu_2028_p3 = ((icmp_ln1494_11_fu_1888_p2[0:0] === 1'b1) ? select_ln340_11_fu_2020_p3 : 6'd0);

assign select_ln1494_12_fu_2180_p3 = ((icmp_ln1494_12_fu_2040_p2[0:0] === 1'b1) ? select_ln340_12_fu_2172_p3 : 6'd0);

assign select_ln1494_13_fu_2332_p3 = ((icmp_ln1494_13_fu_2192_p2[0:0] === 1'b1) ? select_ln340_13_fu_2324_p3 : 6'd0);

assign select_ln1494_14_fu_2484_p3 = ((icmp_ln1494_14_fu_2344_p2[0:0] === 1'b1) ? select_ln340_14_fu_2476_p3 : 6'd0);

assign select_ln1494_15_fu_2636_p3 = ((icmp_ln1494_15_fu_2496_p2[0:0] === 1'b1) ? select_ln340_15_fu_2628_p3 : 6'd0);

assign select_ln1494_16_fu_2788_p3 = ((icmp_ln1494_16_fu_2648_p2[0:0] === 1'b1) ? select_ln340_16_fu_2780_p3 : 6'd0);

assign select_ln1494_17_fu_2940_p3 = ((icmp_ln1494_17_fu_2800_p2[0:0] === 1'b1) ? select_ln340_17_fu_2932_p3 : 6'd0);

assign select_ln1494_18_fu_3092_p3 = ((icmp_ln1494_18_fu_2952_p2[0:0] === 1'b1) ? select_ln340_18_fu_3084_p3 : 6'd0);

assign select_ln1494_19_fu_3244_p3 = ((icmp_ln1494_19_fu_3104_p2[0:0] === 1'b1) ? select_ln340_19_fu_3236_p3 : 6'd0);

assign select_ln1494_1_fu_508_p3 = ((icmp_ln1494_1_fu_368_p2[0:0] === 1'b1) ? select_ln340_1_fu_500_p3 : 6'd0);

assign select_ln1494_2_fu_660_p3 = ((icmp_ln1494_2_fu_520_p2[0:0] === 1'b1) ? select_ln340_2_fu_652_p3 : 6'd0);

assign select_ln1494_3_fu_812_p3 = ((icmp_ln1494_3_fu_672_p2[0:0] === 1'b1) ? select_ln340_3_fu_804_p3 : 6'd0);

assign select_ln1494_4_fu_964_p3 = ((icmp_ln1494_4_fu_824_p2[0:0] === 1'b1) ? select_ln340_4_fu_956_p3 : 6'd0);

assign select_ln1494_5_fu_1116_p3 = ((icmp_ln1494_5_fu_976_p2[0:0] === 1'b1) ? select_ln340_5_fu_1108_p3 : 6'd0);

assign select_ln1494_6_fu_1268_p3 = ((icmp_ln1494_6_fu_1128_p2[0:0] === 1'b1) ? select_ln340_6_fu_1260_p3 : 6'd0);

assign select_ln1494_7_fu_1420_p3 = ((icmp_ln1494_7_fu_1280_p2[0:0] === 1'b1) ? select_ln340_7_fu_1412_p3 : 6'd0);

assign select_ln1494_8_fu_1572_p3 = ((icmp_ln1494_8_fu_1432_p2[0:0] === 1'b1) ? select_ln340_8_fu_1564_p3 : 6'd0);

assign select_ln1494_9_fu_1724_p3 = ((icmp_ln1494_9_fu_1584_p2[0:0] === 1'b1) ? select_ln340_9_fu_1716_p3 : 6'd0);

assign select_ln1494_fu_356_p3 = ((icmp_ln1494_fu_216_p2[0:0] === 1'b1) ? select_ln340_fu_348_p3 : 6'd0);

assign select_ln340_10_fu_1868_p3 = ((or_ln340_10_fu_1862_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_10_fu_1792_p2);

assign select_ln340_11_fu_2020_p3 = ((or_ln340_11_fu_2014_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_11_fu_1944_p2);

assign select_ln340_12_fu_2172_p3 = ((or_ln340_12_fu_2166_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_12_fu_2096_p2);

assign select_ln340_13_fu_2324_p3 = ((or_ln340_13_fu_2318_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_13_fu_2248_p2);

assign select_ln340_14_fu_2476_p3 = ((or_ln340_14_fu_2470_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_14_fu_2400_p2);

assign select_ln340_15_fu_2628_p3 = ((or_ln340_15_fu_2622_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_15_fu_2552_p2);

assign select_ln340_16_fu_2780_p3 = ((or_ln340_16_fu_2774_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_16_fu_2704_p2);

assign select_ln340_17_fu_2932_p3 = ((or_ln340_17_fu_2926_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_17_fu_2856_p2);

assign select_ln340_18_fu_3084_p3 = ((or_ln340_18_fu_3078_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_18_fu_3008_p2);

assign select_ln340_19_fu_3236_p3 = ((or_ln340_19_fu_3230_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_19_fu_3160_p2);

assign select_ln340_1_fu_500_p3 = ((or_ln340_1_fu_494_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_1_fu_424_p2);

assign select_ln340_2_fu_652_p3 = ((or_ln340_2_fu_646_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_2_fu_576_p2);

assign select_ln340_3_fu_804_p3 = ((or_ln340_3_fu_798_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_3_fu_728_p2);

assign select_ln340_4_fu_956_p3 = ((or_ln340_4_fu_950_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_4_fu_880_p2);

assign select_ln340_5_fu_1108_p3 = ((or_ln340_5_fu_1102_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_5_fu_1032_p2);

assign select_ln340_6_fu_1260_p3 = ((or_ln340_6_fu_1254_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_6_fu_1184_p2);

assign select_ln340_7_fu_1412_p3 = ((or_ln340_7_fu_1406_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_7_fu_1336_p2);

assign select_ln340_8_fu_1564_p3 = ((or_ln340_8_fu_1558_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_8_fu_1488_p2);

assign select_ln340_9_fu_1716_p3 = ((or_ln340_9_fu_1710_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_9_fu_1640_p2);

assign select_ln340_fu_348_p3 = ((or_ln340_fu_342_p2[0:0] === 1'b1) ? 6'd63 : add_ln416_fu_272_p2);

assign select_ln777_10_fu_1848_p3 = ((and_ln416_10_fu_1812_p2[0:0] === 1'b1) ? icmp_ln879_10_fu_1836_p2 : icmp_ln768_10_fu_1842_p2);

assign select_ln777_11_fu_2000_p3 = ((and_ln416_11_fu_1964_p2[0:0] === 1'b1) ? icmp_ln879_11_fu_1988_p2 : icmp_ln768_11_fu_1994_p2);

assign select_ln777_12_fu_2152_p3 = ((and_ln416_12_fu_2116_p2[0:0] === 1'b1) ? icmp_ln879_12_fu_2140_p2 : icmp_ln768_12_fu_2146_p2);

assign select_ln777_13_fu_2304_p3 = ((and_ln416_13_fu_2268_p2[0:0] === 1'b1) ? icmp_ln879_13_fu_2292_p2 : icmp_ln768_13_fu_2298_p2);

assign select_ln777_14_fu_2456_p3 = ((and_ln416_14_fu_2420_p2[0:0] === 1'b1) ? icmp_ln879_14_fu_2444_p2 : icmp_ln768_14_fu_2450_p2);

assign select_ln777_15_fu_2608_p3 = ((and_ln416_15_fu_2572_p2[0:0] === 1'b1) ? icmp_ln879_15_fu_2596_p2 : icmp_ln768_15_fu_2602_p2);

assign select_ln777_16_fu_2760_p3 = ((and_ln416_16_fu_2724_p2[0:0] === 1'b1) ? icmp_ln879_16_fu_2748_p2 : icmp_ln768_16_fu_2754_p2);

assign select_ln777_17_fu_2912_p3 = ((and_ln416_17_fu_2876_p2[0:0] === 1'b1) ? icmp_ln879_17_fu_2900_p2 : icmp_ln768_17_fu_2906_p2);

assign select_ln777_18_fu_3064_p3 = ((and_ln416_18_fu_3028_p2[0:0] === 1'b1) ? icmp_ln879_18_fu_3052_p2 : icmp_ln768_18_fu_3058_p2);

assign select_ln777_19_fu_3216_p3 = ((and_ln416_19_fu_3180_p2[0:0] === 1'b1) ? icmp_ln879_19_fu_3204_p2 : icmp_ln768_19_fu_3210_p2);

assign select_ln777_1_fu_480_p3 = ((and_ln416_1_fu_444_p2[0:0] === 1'b1) ? icmp_ln879_1_fu_468_p2 : icmp_ln768_1_fu_474_p2);

assign select_ln777_2_fu_632_p3 = ((and_ln416_2_fu_596_p2[0:0] === 1'b1) ? icmp_ln879_2_fu_620_p2 : icmp_ln768_2_fu_626_p2);

assign select_ln777_3_fu_784_p3 = ((and_ln416_3_fu_748_p2[0:0] === 1'b1) ? icmp_ln879_3_fu_772_p2 : icmp_ln768_3_fu_778_p2);

assign select_ln777_4_fu_936_p3 = ((and_ln416_4_fu_900_p2[0:0] === 1'b1) ? icmp_ln879_4_fu_924_p2 : icmp_ln768_4_fu_930_p2);

assign select_ln777_5_fu_1088_p3 = ((and_ln416_5_fu_1052_p2[0:0] === 1'b1) ? icmp_ln879_5_fu_1076_p2 : icmp_ln768_5_fu_1082_p2);

assign select_ln777_6_fu_1240_p3 = ((and_ln416_6_fu_1204_p2[0:0] === 1'b1) ? icmp_ln879_6_fu_1228_p2 : icmp_ln768_6_fu_1234_p2);

assign select_ln777_7_fu_1392_p3 = ((and_ln416_7_fu_1356_p2[0:0] === 1'b1) ? icmp_ln879_7_fu_1380_p2 : icmp_ln768_7_fu_1386_p2);

assign select_ln777_8_fu_1544_p3 = ((and_ln416_8_fu_1508_p2[0:0] === 1'b1) ? icmp_ln879_8_fu_1532_p2 : icmp_ln768_8_fu_1538_p2);

assign select_ln777_9_fu_1696_p3 = ((and_ln416_9_fu_1660_p2[0:0] === 1'b1) ? icmp_ln879_9_fu_1684_p2 : icmp_ln768_9_fu_1690_p2);

assign select_ln777_fu_328_p3 = ((and_ln416_fu_292_p2[0:0] === 1'b1) ? icmp_ln879_fu_316_p2 : icmp_ln768_fu_322_p2);

assign tmp_100_fu_384_p3 = data_1_V_read[32'd11];

assign tmp_101_fu_392_p3 = data_1_V_read[32'd4];

assign tmp_102_fu_430_p3 = add_ln415_16_fu_418_p2[32'd6];

assign tmp_103_fu_450_p3 = add_ln415_16_fu_418_p2[32'd6];

assign tmp_104_fu_536_p3 = data_2_V_read[32'd11];

assign tmp_105_fu_544_p3 = data_2_V_read[32'd4];

assign tmp_106_fu_582_p3 = add_ln415_17_fu_570_p2[32'd6];

assign tmp_107_fu_602_p3 = add_ln415_17_fu_570_p2[32'd6];

assign tmp_108_fu_688_p3 = data_3_V_read[32'd11];

assign tmp_109_fu_696_p3 = data_3_V_read[32'd4];

assign tmp_110_fu_734_p3 = add_ln415_18_fu_722_p2[32'd6];

assign tmp_111_fu_754_p3 = add_ln415_18_fu_722_p2[32'd6];

assign tmp_112_fu_840_p3 = data_4_V_read[32'd11];

assign tmp_113_fu_848_p3 = data_4_V_read[32'd4];

assign tmp_114_fu_886_p3 = add_ln415_19_fu_874_p2[32'd6];

assign tmp_115_fu_906_p3 = add_ln415_19_fu_874_p2[32'd6];

assign tmp_116_fu_992_p3 = data_5_V_read[32'd11];

assign tmp_117_fu_1000_p3 = data_5_V_read[32'd4];

assign tmp_118_fu_1038_p3 = add_ln415_20_fu_1026_p2[32'd6];

assign tmp_119_fu_1058_p3 = add_ln415_20_fu_1026_p2[32'd6];

assign tmp_120_fu_1144_p3 = data_6_V_read[32'd11];

assign tmp_121_fu_1152_p3 = data_6_V_read[32'd4];

assign tmp_122_fu_1190_p3 = add_ln415_21_fu_1178_p2[32'd6];

assign tmp_123_fu_1210_p3 = add_ln415_21_fu_1178_p2[32'd6];

assign tmp_124_fu_1296_p3 = data_7_V_read[32'd11];

assign tmp_125_fu_1304_p3 = data_7_V_read[32'd4];

assign tmp_126_fu_1342_p3 = add_ln415_22_fu_1330_p2[32'd6];

assign tmp_127_fu_1362_p3 = add_ln415_22_fu_1330_p2[32'd6];

assign tmp_128_fu_1448_p3 = data_8_V_read[32'd11];

assign tmp_129_fu_1456_p3 = data_8_V_read[32'd4];

assign tmp_130_fu_1494_p3 = add_ln415_23_fu_1482_p2[32'd6];

assign tmp_131_fu_1514_p3 = add_ln415_23_fu_1482_p2[32'd6];

assign tmp_132_fu_1600_p3 = data_9_V_read[32'd11];

assign tmp_133_fu_1608_p3 = data_9_V_read[32'd4];

assign tmp_134_fu_1646_p3 = add_ln415_24_fu_1634_p2[32'd6];

assign tmp_135_fu_1666_p3 = add_ln415_24_fu_1634_p2[32'd6];

assign tmp_136_fu_1752_p3 = data_10_V_read[32'd11];

assign tmp_137_fu_1760_p3 = data_10_V_read[32'd4];

assign tmp_138_fu_1798_p3 = add_ln415_25_fu_1786_p2[32'd6];

assign tmp_139_fu_1818_p3 = add_ln415_25_fu_1786_p2[32'd6];

assign tmp_140_fu_1904_p3 = data_11_V_read[32'd11];

assign tmp_141_fu_1912_p3 = data_11_V_read[32'd4];

assign tmp_142_fu_1950_p3 = add_ln415_26_fu_1938_p2[32'd6];

assign tmp_143_fu_1970_p3 = add_ln415_26_fu_1938_p2[32'd6];

assign tmp_144_fu_2056_p3 = data_12_V_read[32'd11];

assign tmp_145_fu_2064_p3 = data_12_V_read[32'd4];

assign tmp_146_fu_2102_p3 = add_ln415_27_fu_2090_p2[32'd6];

assign tmp_147_fu_2122_p3 = add_ln415_27_fu_2090_p2[32'd6];

assign tmp_148_fu_2208_p3 = data_13_V_read[32'd11];

assign tmp_149_fu_2216_p3 = data_13_V_read[32'd4];

assign tmp_150_fu_2254_p3 = add_ln415_28_fu_2242_p2[32'd6];

assign tmp_151_fu_2274_p3 = add_ln415_28_fu_2242_p2[32'd6];

assign tmp_152_fu_2360_p3 = data_14_V_read[32'd11];

assign tmp_153_fu_2368_p3 = data_14_V_read[32'd4];

assign tmp_154_fu_2406_p3 = add_ln415_29_fu_2394_p2[32'd6];

assign tmp_155_fu_2426_p3 = add_ln415_29_fu_2394_p2[32'd6];

assign tmp_156_fu_2512_p3 = data_15_V_read[32'd11];

assign tmp_157_fu_2520_p3 = data_15_V_read[32'd4];

assign tmp_158_fu_2558_p3 = add_ln415_30_fu_2546_p2[32'd6];

assign tmp_159_fu_2578_p3 = add_ln415_30_fu_2546_p2[32'd6];

assign tmp_160_fu_2664_p3 = data_16_V_read[32'd11];

assign tmp_161_fu_2672_p3 = data_16_V_read[32'd4];

assign tmp_162_fu_2710_p3 = add_ln415_31_fu_2698_p2[32'd6];

assign tmp_163_fu_2730_p3 = add_ln415_31_fu_2698_p2[32'd6];

assign tmp_164_fu_2816_p3 = data_17_V_read[32'd11];

assign tmp_165_fu_2824_p3 = data_17_V_read[32'd4];

assign tmp_166_fu_2862_p3 = add_ln415_32_fu_2850_p2[32'd6];

assign tmp_167_fu_2882_p3 = add_ln415_32_fu_2850_p2[32'd6];

assign tmp_168_fu_2968_p3 = data_18_V_read[32'd11];

assign tmp_169_fu_2976_p3 = data_18_V_read[32'd4];

assign tmp_170_fu_3014_p3 = add_ln415_33_fu_3002_p2[32'd6];

assign tmp_171_fu_3034_p3 = add_ln415_33_fu_3002_p2[32'd6];

assign tmp_172_fu_3120_p3 = data_19_V_read[32'd11];

assign tmp_173_fu_3128_p3 = data_19_V_read[32'd4];

assign tmp_174_fu_3166_p3 = add_ln415_34_fu_3154_p2[32'd6];

assign tmp_175_fu_3186_p3 = add_ln415_34_fu_3154_p2[32'd6];

assign tmp_96_fu_232_p3 = data_0_V_read[32'd11];

assign tmp_97_fu_240_p3 = data_0_V_read[32'd4];

assign tmp_98_fu_278_p3 = add_ln415_fu_266_p2[32'd6];

assign tmp_99_fu_298_p3 = add_ln415_fu_266_p2[32'd6];

assign trunc_ln415_10_fu_1776_p4 = {{data_10_V_read[10:5]}};

assign trunc_ln415_11_fu_1928_p4 = {{data_11_V_read[10:5]}};

assign trunc_ln415_12_fu_2080_p4 = {{data_12_V_read[10:5]}};

assign trunc_ln415_13_fu_2232_p4 = {{data_13_V_read[10:5]}};

assign trunc_ln415_14_fu_2384_p4 = {{data_14_V_read[10:5]}};

assign trunc_ln415_15_fu_2536_p4 = {{data_15_V_read[10:5]}};

assign trunc_ln415_16_fu_2688_p4 = {{data_16_V_read[10:5]}};

assign trunc_ln415_17_fu_2840_p4 = {{data_17_V_read[10:5]}};

assign trunc_ln415_18_fu_2992_p4 = {{data_18_V_read[10:5]}};

assign trunc_ln415_19_fu_3144_p4 = {{data_19_V_read[10:5]}};

assign trunc_ln415_1_fu_408_p4 = {{data_1_V_read[10:5]}};

assign trunc_ln415_2_fu_560_p4 = {{data_2_V_read[10:5]}};

assign trunc_ln415_3_fu_712_p4 = {{data_3_V_read[10:5]}};

assign trunc_ln415_4_fu_864_p4 = {{data_4_V_read[10:5]}};

assign trunc_ln415_5_fu_1016_p4 = {{data_5_V_read[10:5]}};

assign trunc_ln415_6_fu_1168_p4 = {{data_6_V_read[10:5]}};

assign trunc_ln415_7_fu_1320_p4 = {{data_7_V_read[10:5]}};

assign trunc_ln415_8_fu_1472_p4 = {{data_8_V_read[10:5]}};

assign trunc_ln415_9_fu_1624_p4 = {{data_9_V_read[10:5]}};

assign trunc_ln415_s_fu_256_p4 = {{data_0_V_read[10:5]}};

assign trunc_ln708_10_fu_1894_p4 = {{data_11_V_read[11:5]}};

assign trunc_ln708_11_fu_2046_p4 = {{data_12_V_read[11:5]}};

assign trunc_ln708_12_fu_2198_p4 = {{data_13_V_read[11:5]}};

assign trunc_ln708_13_fu_2350_p4 = {{data_14_V_read[11:5]}};

assign trunc_ln708_14_fu_2502_p4 = {{data_15_V_read[11:5]}};

assign trunc_ln708_15_fu_2654_p4 = {{data_16_V_read[11:5]}};

assign trunc_ln708_16_fu_2806_p4 = {{data_17_V_read[11:5]}};

assign trunc_ln708_17_fu_2958_p4 = {{data_18_V_read[11:5]}};

assign trunc_ln708_18_fu_3110_p4 = {{data_19_V_read[11:5]}};

assign trunc_ln708_1_fu_526_p4 = {{data_2_V_read[11:5]}};

assign trunc_ln708_2_fu_678_p4 = {{data_3_V_read[11:5]}};

assign trunc_ln708_3_fu_830_p4 = {{data_4_V_read[11:5]}};

assign trunc_ln708_4_fu_982_p4 = {{data_5_V_read[11:5]}};

assign trunc_ln708_5_fu_1134_p4 = {{data_6_V_read[11:5]}};

assign trunc_ln708_6_fu_1286_p4 = {{data_7_V_read[11:5]}};

assign trunc_ln708_7_fu_1438_p4 = {{data_8_V_read[11:5]}};

assign trunc_ln708_8_fu_1590_p4 = {{data_9_V_read[11:5]}};

assign trunc_ln708_9_fu_1742_p4 = {{data_10_V_read[11:5]}};

assign trunc_ln708_s_fu_374_p4 = {{data_1_V_read[11:5]}};

assign trunc_ln_fu_222_p4 = {{data_0_V_read[11:5]}};

assign xor_ln416_10_fu_1806_p2 = (tmp_138_fu_1798_p3 ^ 1'd1);

assign xor_ln416_11_fu_1958_p2 = (tmp_142_fu_1950_p3 ^ 1'd1);

assign xor_ln416_12_fu_2110_p2 = (tmp_146_fu_2102_p3 ^ 1'd1);

assign xor_ln416_13_fu_2262_p2 = (tmp_150_fu_2254_p3 ^ 1'd1);

assign xor_ln416_14_fu_2414_p2 = (tmp_154_fu_2406_p3 ^ 1'd1);

assign xor_ln416_15_fu_2566_p2 = (tmp_158_fu_2558_p3 ^ 1'd1);

assign xor_ln416_16_fu_2718_p2 = (tmp_162_fu_2710_p3 ^ 1'd1);

assign xor_ln416_17_fu_2870_p2 = (tmp_166_fu_2862_p3 ^ 1'd1);

assign xor_ln416_18_fu_3022_p2 = (tmp_170_fu_3014_p3 ^ 1'd1);

assign xor_ln416_19_fu_3174_p2 = (tmp_174_fu_3166_p3 ^ 1'd1);

assign xor_ln416_1_fu_438_p2 = (tmp_102_fu_430_p3 ^ 1'd1);

assign xor_ln416_2_fu_590_p2 = (tmp_106_fu_582_p3 ^ 1'd1);

assign xor_ln416_3_fu_742_p2 = (tmp_110_fu_734_p3 ^ 1'd1);

assign xor_ln416_4_fu_894_p2 = (tmp_114_fu_886_p3 ^ 1'd1);

assign xor_ln416_5_fu_1046_p2 = (tmp_118_fu_1038_p3 ^ 1'd1);

assign xor_ln416_6_fu_1198_p2 = (tmp_122_fu_1190_p3 ^ 1'd1);

assign xor_ln416_7_fu_1350_p2 = (tmp_126_fu_1342_p3 ^ 1'd1);

assign xor_ln416_8_fu_1502_p2 = (tmp_130_fu_1494_p3 ^ 1'd1);

assign xor_ln416_9_fu_1654_p2 = (tmp_134_fu_1646_p3 ^ 1'd1);

assign xor_ln416_fu_286_p2 = (tmp_98_fu_278_p3 ^ 1'd1);

assign xor_ln785_10_fu_1856_p2 = (select_ln777_10_fu_1848_p3 ^ 1'd1);

assign xor_ln785_11_fu_2008_p2 = (select_ln777_11_fu_2000_p3 ^ 1'd1);

assign xor_ln785_12_fu_2160_p2 = (select_ln777_12_fu_2152_p3 ^ 1'd1);

assign xor_ln785_13_fu_2312_p2 = (select_ln777_13_fu_2304_p3 ^ 1'd1);

assign xor_ln785_14_fu_2464_p2 = (select_ln777_14_fu_2456_p3 ^ 1'd1);

assign xor_ln785_15_fu_2616_p2 = (select_ln777_15_fu_2608_p3 ^ 1'd1);

assign xor_ln785_16_fu_2768_p2 = (select_ln777_16_fu_2760_p3 ^ 1'd1);

assign xor_ln785_17_fu_2920_p2 = (select_ln777_17_fu_2912_p3 ^ 1'd1);

assign xor_ln785_18_fu_3072_p2 = (select_ln777_18_fu_3064_p3 ^ 1'd1);

assign xor_ln785_19_fu_3224_p2 = (select_ln777_19_fu_3216_p3 ^ 1'd1);

assign xor_ln785_1_fu_488_p2 = (select_ln777_1_fu_480_p3 ^ 1'd1);

assign xor_ln785_2_fu_640_p2 = (select_ln777_2_fu_632_p3 ^ 1'd1);

assign xor_ln785_3_fu_792_p2 = (select_ln777_3_fu_784_p3 ^ 1'd1);

assign xor_ln785_4_fu_944_p2 = (select_ln777_4_fu_936_p3 ^ 1'd1);

assign xor_ln785_5_fu_1096_p2 = (select_ln777_5_fu_1088_p3 ^ 1'd1);

assign xor_ln785_6_fu_1248_p2 = (select_ln777_6_fu_1240_p3 ^ 1'd1);

assign xor_ln785_7_fu_1400_p2 = (select_ln777_7_fu_1392_p3 ^ 1'd1);

assign xor_ln785_8_fu_1552_p2 = (select_ln777_8_fu_1544_p3 ^ 1'd1);

assign xor_ln785_9_fu_1704_p2 = (select_ln777_9_fu_1696_p3 ^ 1'd1);

assign xor_ln785_fu_336_p2 = (select_ln777_fu_328_p3 ^ 1'd1);

assign zext_ln1494_10_fu_1884_p1 = select_ln1494_10_fu_1876_p3;

assign zext_ln1494_11_fu_2036_p1 = select_ln1494_11_fu_2028_p3;

assign zext_ln1494_12_fu_2188_p1 = select_ln1494_12_fu_2180_p3;

assign zext_ln1494_13_fu_2340_p1 = select_ln1494_13_fu_2332_p3;

assign zext_ln1494_14_fu_2492_p1 = select_ln1494_14_fu_2484_p3;

assign zext_ln1494_15_fu_2644_p1 = select_ln1494_15_fu_2636_p3;

assign zext_ln1494_16_fu_2796_p1 = select_ln1494_16_fu_2788_p3;

assign zext_ln1494_17_fu_2948_p1 = select_ln1494_17_fu_2940_p3;

assign zext_ln1494_18_fu_3100_p1 = select_ln1494_18_fu_3092_p3;

assign zext_ln1494_19_fu_3252_p1 = select_ln1494_19_fu_3244_p3;

assign zext_ln1494_1_fu_516_p1 = select_ln1494_1_fu_508_p3;

assign zext_ln1494_2_fu_668_p1 = select_ln1494_2_fu_660_p3;

assign zext_ln1494_3_fu_820_p1 = select_ln1494_3_fu_812_p3;

assign zext_ln1494_4_fu_972_p1 = select_ln1494_4_fu_964_p3;

assign zext_ln1494_5_fu_1124_p1 = select_ln1494_5_fu_1116_p3;

assign zext_ln1494_6_fu_1276_p1 = select_ln1494_6_fu_1268_p3;

assign zext_ln1494_7_fu_1428_p1 = select_ln1494_7_fu_1420_p3;

assign zext_ln1494_8_fu_1580_p1 = select_ln1494_8_fu_1572_p3;

assign zext_ln1494_9_fu_1732_p1 = select_ln1494_9_fu_1724_p3;

assign zext_ln1494_fu_364_p1 = select_ln1494_fu_356_p3;

assign zext_ln415_32_fu_252_p1 = tmp_97_fu_240_p3;

assign zext_ln415_33_fu_400_p1 = tmp_101_fu_392_p3;

assign zext_ln415_34_fu_404_p1 = tmp_101_fu_392_p3;

assign zext_ln415_35_fu_552_p1 = tmp_105_fu_544_p3;

assign zext_ln415_36_fu_556_p1 = tmp_105_fu_544_p3;

assign zext_ln415_37_fu_704_p1 = tmp_109_fu_696_p3;

assign zext_ln415_38_fu_708_p1 = tmp_109_fu_696_p3;

assign zext_ln415_39_fu_856_p1 = tmp_113_fu_848_p3;

assign zext_ln415_40_fu_860_p1 = tmp_113_fu_848_p3;

assign zext_ln415_41_fu_1008_p1 = tmp_117_fu_1000_p3;

assign zext_ln415_42_fu_1012_p1 = tmp_117_fu_1000_p3;

assign zext_ln415_43_fu_1160_p1 = tmp_121_fu_1152_p3;

assign zext_ln415_44_fu_1164_p1 = tmp_121_fu_1152_p3;

assign zext_ln415_45_fu_1312_p1 = tmp_125_fu_1304_p3;

assign zext_ln415_46_fu_1316_p1 = tmp_125_fu_1304_p3;

assign zext_ln415_47_fu_1464_p1 = tmp_129_fu_1456_p3;

assign zext_ln415_48_fu_1468_p1 = tmp_129_fu_1456_p3;

assign zext_ln415_49_fu_1616_p1 = tmp_133_fu_1608_p3;

assign zext_ln415_50_fu_1620_p1 = tmp_133_fu_1608_p3;

assign zext_ln415_51_fu_1768_p1 = tmp_137_fu_1760_p3;

assign zext_ln415_52_fu_1772_p1 = tmp_137_fu_1760_p3;

assign zext_ln415_53_fu_1920_p1 = tmp_141_fu_1912_p3;

assign zext_ln415_54_fu_1924_p1 = tmp_141_fu_1912_p3;

assign zext_ln415_55_fu_2072_p1 = tmp_145_fu_2064_p3;

assign zext_ln415_56_fu_2076_p1 = tmp_145_fu_2064_p3;

assign zext_ln415_57_fu_2224_p1 = tmp_149_fu_2216_p3;

assign zext_ln415_58_fu_2228_p1 = tmp_149_fu_2216_p3;

assign zext_ln415_59_fu_2376_p1 = tmp_153_fu_2368_p3;

assign zext_ln415_60_fu_2380_p1 = tmp_153_fu_2368_p3;

assign zext_ln415_61_fu_2528_p1 = tmp_157_fu_2520_p3;

assign zext_ln415_62_fu_2532_p1 = tmp_157_fu_2520_p3;

assign zext_ln415_63_fu_2680_p1 = tmp_161_fu_2672_p3;

assign zext_ln415_64_fu_2684_p1 = tmp_161_fu_2672_p3;

assign zext_ln415_65_fu_2832_p1 = tmp_165_fu_2824_p3;

assign zext_ln415_66_fu_2836_p1 = tmp_165_fu_2824_p3;

assign zext_ln415_67_fu_2984_p1 = tmp_169_fu_2976_p3;

assign zext_ln415_68_fu_2988_p1 = tmp_169_fu_2976_p3;

assign zext_ln415_69_fu_3136_p1 = tmp_173_fu_3128_p3;

assign zext_ln415_70_fu_3140_p1 = tmp_173_fu_3128_p3;

assign zext_ln415_fu_248_p1 = tmp_97_fu_240_p3;

endmodule //relu
