// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module normalize_0_0_0_0_0_s (
        ap_ready,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11
);


output   ap_ready;
input  [59:0] data_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;

wire   [4:0] mul_ln731_1_fu_104_p1;
wire   [4:0] mul_ln731_7_fu_106_p1;
wire   [4:0] mul_ln731_4_fu_107_p1;
wire   [4:0] mul_ln731_fu_108_p1;
wire   [4:0] mul_ln731_3_fu_109_p1;
wire   [4:0] mul_ln731_5_fu_111_p1;
wire   [4:0] mul_ln731_6_fu_112_p1;
wire   [4:0] mul_ln731_2_fu_114_p1;
wire   [4:0] trunc_ln446_fu_557_p1;
wire   [11:0] mul_ln731_fu_108_p2;
wire   [11:0] add_ln731_fu_566_p2;
wire   [12:0] tmp_1_fu_572_p3;
wire   [4:0] tmp_5_fu_584_p4;
wire   [11:0] shl_ln731_s_fu_594_p3;
wire   [7:0] shl_ln731_1_fu_606_p3;
wire   [12:0] zext_ln731_1_fu_602_p1;
wire   [12:0] zext_ln731_2_fu_614_p1;
wire   [12:0] sub_ln731_fu_618_p2;
wire   [12:0] add_ln731_1_fu_624_p2;
wire   [13:0] tmp_8_fu_630_p3;
wire   [4:0] tmp_3_fu_642_p4;
wire   [9:0] mul_ln731_1_fu_104_p2;
wire   [9:0] add_ln731_2_fu_657_p2;
wire   [10:0] tmp_10_fu_663_p3;
wire   [4:0] tmp_4_fu_675_p4;
wire   [11:0] mul_ln731_2_fu_114_p2;
wire   [11:0] add_ln731_3_fu_690_p2;
wire   [12:0] tmp_11_fu_696_p3;
wire   [4:0] tmp_12_fu_708_p4;
wire   [11:0] shl_ln731_2_fu_718_p3;
wire   [7:0] shl_ln731_3_fu_730_p3;
wire   [12:0] zext_ln731_5_fu_726_p1;
wire   [12:0] zext_ln731_6_fu_738_p1;
wire   [12:0] sub_ln731_1_fu_742_p2;
wire   [12:0] add_ln731_4_fu_748_p2;
wire   [13:0] tmp_13_fu_754_p3;
wire   [4:0] tmp_6_fu_766_p4;
wire   [9:0] mul_ln731_3_fu_109_p2;
wire   [9:0] add_ln731_5_fu_781_p2;
wire   [10:0] tmp_14_fu_787_p3;
wire   [4:0] tmp_7_fu_799_p4;
wire   [11:0] mul_ln731_4_fu_107_p2;
wire   [11:0] add_ln731_6_fu_814_p2;
wire   [12:0] tmp_15_fu_820_p3;
wire   [4:0] tmp_16_fu_832_p4;
wire   [11:0] shl_ln731_4_fu_842_p3;
wire   [7:0] shl_ln731_5_fu_854_p3;
wire   [12:0] zext_ln731_9_fu_850_p1;
wire   [12:0] zext_ln731_10_fu_862_p1;
wire   [12:0] sub_ln731_2_fu_866_p2;
wire   [12:0] add_ln731_7_fu_872_p2;
wire   [13:0] tmp_17_fu_878_p3;
wire   [4:0] tmp_9_fu_890_p4;
wire   [9:0] mul_ln731_5_fu_111_p2;
wire   [9:0] add_ln731_8_fu_905_p2;
wire   [10:0] tmp_18_fu_911_p3;
wire   [4:0] tmp_s_fu_923_p4;
wire   [11:0] mul_ln731_6_fu_112_p2;
wire   [11:0] add_ln731_9_fu_938_p2;
wire   [12:0] tmp_19_fu_944_p3;
wire   [4:0] tmp_20_fu_956_p4;
wire   [11:0] shl_ln731_6_fu_966_p3;
wire   [7:0] shl_ln731_7_fu_978_p3;
wire   [12:0] zext_ln731_13_fu_974_p1;
wire   [12:0] zext_ln731_14_fu_986_p1;
wire   [12:0] sub_ln731_3_fu_990_p2;
wire   [12:0] add_ln731_10_fu_996_p2;
wire   [13:0] tmp_21_fu_1002_p3;
wire   [4:0] tmp_2_fu_1014_p4;
wire   [9:0] mul_ln731_7_fu_106_p2;
wire   [9:0] add_ln731_11_fu_1029_p2;
wire   [10:0] tmp_22_fu_1035_p3;
wire  signed [15:0] sext_ln731_fu_580_p1;
wire  signed [15:0] sext_ln731_1_fu_638_p1;
wire  signed [15:0] sext_ln731_2_fu_671_p1;
wire  signed [15:0] sext_ln731_3_fu_704_p1;
wire  signed [15:0] sext_ln731_4_fu_762_p1;
wire  signed [15:0] sext_ln731_5_fu_795_p1;
wire  signed [15:0] sext_ln731_6_fu_828_p1;
wire  signed [15:0] sext_ln731_7_fu_886_p1;
wire  signed [15:0] sext_ln731_8_fu_919_p1;
wire  signed [15:0] sext_ln731_9_fu_952_p1;
wire  signed [15:0] sext_ln731_10_fu_1010_p1;
wire  signed [15:0] sext_ln731_11_fu_1043_p1;
wire   [9:0] mul_ln731_1_fu_104_p10;
wire   [11:0] mul_ln731_2_fu_114_p10;
wire   [9:0] mul_ln731_3_fu_109_p10;
wire   [11:0] mul_ln731_4_fu_107_p10;
wire   [9:0] mul_ln731_5_fu_111_p10;
wire   [11:0] mul_ln731_6_fu_112_p10;
wire   [9:0] mul_ln731_7_fu_106_p10;
wire   [11:0] mul_ln731_fu_108_p10;

assign add_ln731_10_fu_996_p2 = ($signed(13'd7317) + $signed(sub_ln731_3_fu_990_p2));

assign add_ln731_11_fu_1029_p2 = ($signed(10'd641) + $signed(mul_ln731_7_fu_106_p2));

assign add_ln731_1_fu_624_p2 = ($signed(13'd7317) + $signed(sub_ln731_fu_618_p2));

assign add_ln731_2_fu_657_p2 = ($signed(10'd641) + $signed(mul_ln731_1_fu_104_p2));

assign add_ln731_3_fu_690_p2 = ($signed(12'd2621) + $signed(mul_ln731_2_fu_114_p2));

assign add_ln731_4_fu_748_p2 = ($signed(13'd7317) + $signed(sub_ln731_1_fu_742_p2));

assign add_ln731_5_fu_781_p2 = ($signed(10'd641) + $signed(mul_ln731_3_fu_109_p2));

assign add_ln731_6_fu_814_p2 = ($signed(12'd2621) + $signed(mul_ln731_4_fu_107_p2));

assign add_ln731_7_fu_872_p2 = ($signed(13'd7317) + $signed(sub_ln731_2_fu_866_p2));

assign add_ln731_8_fu_905_p2 = ($signed(10'd641) + $signed(mul_ln731_5_fu_111_p2));

assign add_ln731_9_fu_938_p2 = ($signed(12'd2621) + $signed(mul_ln731_6_fu_112_p2));

assign add_ln731_fu_566_p2 = ($signed(12'd2621) + $signed(mul_ln731_fu_108_p2));

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln731_fu_580_p1;

assign ap_return_1 = sext_ln731_1_fu_638_p1;

assign ap_return_10 = sext_ln731_10_fu_1010_p1;

assign ap_return_11 = sext_ln731_11_fu_1043_p1;

assign ap_return_2 = sext_ln731_2_fu_671_p1;

assign ap_return_3 = sext_ln731_3_fu_704_p1;

assign ap_return_4 = sext_ln731_4_fu_762_p1;

assign ap_return_5 = sext_ln731_5_fu_795_p1;

assign ap_return_6 = sext_ln731_6_fu_828_p1;

assign ap_return_7 = sext_ln731_7_fu_886_p1;

assign ap_return_8 = sext_ln731_8_fu_919_p1;

assign ap_return_9 = sext_ln731_9_fu_952_p1;

assign mul_ln731_1_fu_104_p1 = mul_ln731_1_fu_104_p10;

assign mul_ln731_1_fu_104_p10 = tmp_3_fu_642_p4;

assign mul_ln731_1_fu_104_p2 = (10'd27 * mul_ln731_1_fu_104_p1);

assign mul_ln731_2_fu_114_p1 = mul_ln731_2_fu_114_p10;

assign mul_ln731_2_fu_114_p10 = tmp_4_fu_675_p4;

assign mul_ln731_2_fu_114_p2 = (12'd98 * mul_ln731_2_fu_114_p1);

assign mul_ln731_3_fu_109_p1 = mul_ln731_3_fu_109_p10;

assign mul_ln731_3_fu_109_p10 = tmp_6_fu_766_p4;

assign mul_ln731_3_fu_109_p2 = (10'd27 * mul_ln731_3_fu_109_p1);

assign mul_ln731_4_fu_107_p1 = mul_ln731_4_fu_107_p10;

assign mul_ln731_4_fu_107_p10 = tmp_7_fu_799_p4;

assign mul_ln731_4_fu_107_p2 = (12'd98 * mul_ln731_4_fu_107_p1);

assign mul_ln731_5_fu_111_p1 = mul_ln731_5_fu_111_p10;

assign mul_ln731_5_fu_111_p10 = tmp_9_fu_890_p4;

assign mul_ln731_5_fu_111_p2 = (10'd27 * mul_ln731_5_fu_111_p1);

assign mul_ln731_6_fu_112_p1 = mul_ln731_6_fu_112_p10;

assign mul_ln731_6_fu_112_p10 = tmp_s_fu_923_p4;

assign mul_ln731_6_fu_112_p2 = (12'd98 * mul_ln731_6_fu_112_p1);

assign mul_ln731_7_fu_106_p1 = mul_ln731_7_fu_106_p10;

assign mul_ln731_7_fu_106_p10 = tmp_2_fu_1014_p4;

assign mul_ln731_7_fu_106_p2 = (10'd27 * mul_ln731_7_fu_106_p1);

assign mul_ln731_fu_108_p1 = mul_ln731_fu_108_p10;

assign mul_ln731_fu_108_p10 = trunc_ln446_fu_557_p1;

assign mul_ln731_fu_108_p2 = (12'd98 * mul_ln731_fu_108_p1);

assign sext_ln731_10_fu_1010_p1 = $signed(tmp_21_fu_1002_p3);

assign sext_ln731_11_fu_1043_p1 = $signed(tmp_22_fu_1035_p3);

assign sext_ln731_1_fu_638_p1 = $signed(tmp_8_fu_630_p3);

assign sext_ln731_2_fu_671_p1 = $signed(tmp_10_fu_663_p3);

assign sext_ln731_3_fu_704_p1 = $signed(tmp_11_fu_696_p3);

assign sext_ln731_4_fu_762_p1 = $signed(tmp_13_fu_754_p3);

assign sext_ln731_5_fu_795_p1 = $signed(tmp_14_fu_787_p3);

assign sext_ln731_6_fu_828_p1 = $signed(tmp_15_fu_820_p3);

assign sext_ln731_7_fu_886_p1 = $signed(tmp_17_fu_878_p3);

assign sext_ln731_8_fu_919_p1 = $signed(tmp_18_fu_911_p3);

assign sext_ln731_9_fu_952_p1 = $signed(tmp_19_fu_944_p3);

assign sext_ln731_fu_580_p1 = $signed(tmp_1_fu_572_p3);

assign shl_ln731_1_fu_606_p3 = {{tmp_5_fu_584_p4}, {3'd0}};

assign shl_ln731_2_fu_718_p3 = {{tmp_12_fu_708_p4}, {7'd0}};

assign shl_ln731_3_fu_730_p3 = {{tmp_12_fu_708_p4}, {3'd0}};

assign shl_ln731_4_fu_842_p3 = {{tmp_16_fu_832_p4}, {7'd0}};

assign shl_ln731_5_fu_854_p3 = {{tmp_16_fu_832_p4}, {3'd0}};

assign shl_ln731_6_fu_966_p3 = {{tmp_20_fu_956_p4}, {7'd0}};

assign shl_ln731_7_fu_978_p3 = {{tmp_20_fu_956_p4}, {3'd0}};

assign shl_ln731_s_fu_594_p3 = {{tmp_5_fu_584_p4}, {7'd0}};

assign sub_ln731_1_fu_742_p2 = (zext_ln731_5_fu_726_p1 - zext_ln731_6_fu_738_p1);

assign sub_ln731_2_fu_866_p2 = (zext_ln731_9_fu_850_p1 - zext_ln731_10_fu_862_p1);

assign sub_ln731_3_fu_990_p2 = (zext_ln731_13_fu_974_p1 - zext_ln731_14_fu_986_p1);

assign sub_ln731_fu_618_p2 = (zext_ln731_1_fu_602_p1 - zext_ln731_2_fu_614_p1);

assign tmp_10_fu_663_p3 = {{add_ln731_2_fu_657_p2}, {1'd0}};

assign tmp_11_fu_696_p3 = {{add_ln731_3_fu_690_p2}, {1'd0}};

assign tmp_12_fu_708_p4 = {{data_V_read[24:20]}};

assign tmp_13_fu_754_p3 = {{add_ln731_4_fu_748_p2}, {1'd0}};

assign tmp_14_fu_787_p3 = {{add_ln731_5_fu_781_p2}, {1'd0}};

assign tmp_15_fu_820_p3 = {{add_ln731_6_fu_814_p2}, {1'd0}};

assign tmp_16_fu_832_p4 = {{data_V_read[39:35]}};

assign tmp_17_fu_878_p3 = {{add_ln731_7_fu_872_p2}, {1'd0}};

assign tmp_18_fu_911_p3 = {{add_ln731_8_fu_905_p2}, {1'd0}};

assign tmp_19_fu_944_p3 = {{add_ln731_9_fu_938_p2}, {1'd0}};

assign tmp_1_fu_572_p3 = {{add_ln731_fu_566_p2}, {1'd0}};

assign tmp_20_fu_956_p4 = {{data_V_read[54:50]}};

assign tmp_21_fu_1002_p3 = {{add_ln731_10_fu_996_p2}, {1'd0}};

assign tmp_22_fu_1035_p3 = {{add_ln731_11_fu_1029_p2}, {1'd0}};

assign tmp_2_fu_1014_p4 = {{data_V_read[59:55]}};

assign tmp_3_fu_642_p4 = {{data_V_read[14:10]}};

assign tmp_4_fu_675_p4 = {{data_V_read[19:15]}};

assign tmp_5_fu_584_p4 = {{data_V_read[9:5]}};

assign tmp_6_fu_766_p4 = {{data_V_read[29:25]}};

assign tmp_7_fu_799_p4 = {{data_V_read[34:30]}};

assign tmp_8_fu_630_p3 = {{add_ln731_1_fu_624_p2}, {1'd0}};

assign tmp_9_fu_890_p4 = {{data_V_read[44:40]}};

assign tmp_s_fu_923_p4 = {{data_V_read[49:45]}};

assign trunc_ln446_fu_557_p1 = data_V_read[4:0];

assign zext_ln731_10_fu_862_p1 = shl_ln731_5_fu_854_p3;

assign zext_ln731_13_fu_974_p1 = shl_ln731_6_fu_966_p3;

assign zext_ln731_14_fu_986_p1 = shl_ln731_7_fu_978_p3;

assign zext_ln731_1_fu_602_p1 = shl_ln731_s_fu_594_p3;

assign zext_ln731_2_fu_614_p1 = shl_ln731_1_fu_606_p3;

assign zext_ln731_5_fu_726_p1 = shl_ln731_2_fu_718_p3;

assign zext_ln731_6_fu_738_p1 = shl_ln731_3_fu_730_p3;

assign zext_ln731_9_fu_850_p1 = shl_ln731_4_fu_842_p3;

endmodule //normalize_0_0_0_0_0_s
